#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/redis_gateway
LOG_DIR=/var/vcap/sys/log/redis_gateway
JOB_DIR=/var/vcap/jobs/redis_gateway

PIDFILE=$RUN_DIR/redis_gateway.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Redis gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/redis_gateway/services/ng/redis/bin/redis_gateway \
         -c $JOB_DIR/config/redis_gateway.yml \
         >>$LOG_DIR/redis_gateway.stdout.log \
         2>>$LOG_DIR/redis_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: redis_gateway_ctl {start|stop}"

    ;;

esac
