#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/service_broker
LOG_DIR=/var/vcap/sys/log/service_broker
PIDFILE=$RUN_DIR/service_broker.pid
JOB_DIR=/var/vcap/jobs/service_broker
SQLITE_DIR=/var/vcap/store

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Service broker"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SQLITE_DIR

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    echo $$ > $PIDFILE

    exec /var/vcap/packages/service_broker/bin/services/service_broker \
         -c $JOB_DIR/config/service_broker.yml \
         -p $JOB_DIR/config/pre_defined_services.yml \
         >>$LOG_DIR/service_broker.stdout.log \
         2>>$LOG_DIR/service_broker.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: service_broker_ctl {start|stop}"

    ;;

esac
