#!/bin/bash

RUN_DIR=/var/vcap/sys/run/nginx_router
LOG_DIR=/var/vcap/sys/log/nginx_router
PIDFILE=$RUN_DIR/nginx.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Nginx"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    export LUA_PATH="/var/vcap/packages/router/ext/nginx/?.lua"
    export LUA_CPATH="/var/vcap/packages/nginx/lib/?.so"

    exec /var/vcap/packages/nginx/sbin/nginx \
         -c /var/vcap/jobs/router/config/nginx.conf \
         >>$LOG_DIR/nginx.stdout.log \
         2>>$LOG_DIR/nginx.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"

    ;;

esac
