image: cloudfoundry/cf-release-pipeline

cache:
  - output
  - .blobs
  - /root/.m2
script:
  - source /usr/local/share/chruby/chruby.sh
  - chruby ruby-1.9.3-p547
  - ./scripts/drone/create-dev-release.sh
