#!/bin/sh

set -e -x

VERSION=$1

if [ -z $VERSION ]; then
  echo "Please specify Ruby version."
  exit 1
fi

./update

for ver in `find src/ -name .ruby-version -maxdepth 3`; do
  echo $VERSION > $ver

  pushd $(dirname $ver)
    git checkout master
    git pull origin master
    git add .ruby-version
    git ci -m "bump ruby version to $VERSION"
    git push origin master
  popd
done

git add src/
echo $VERSION > .ruby-version
git add .ruby-version
git ci -m "`./staged_shortlog`"
