#!/bin/sh

>&2 echo "WARNING: The './generate_deployment_manifest' file is deprecated and will be removed. Please use './scripts/generate_deployment_manifest' instead."

templates=$(dirname $0)/templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "openstack" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|openstack|warden|vsphere> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/cf-deployment.yml \
  $templates/cf-resource-pools.yml \
  $templates/cf-jobs.yml \
  $templates/cf-properties.yml \
  $templates/cf-lamb.yml \
  $templates/cf-infrastructure-${infrastructure}.yml \
  "$@"
