#!/usr/bin/env ruby
require_relative 'check_travis.rb'

diffs = `git diff --cached`.split('diff --git').select { |log| log =~ /Subproject/ }

diffs.each do |diff|
  /a\/(?<loc>.+?)\sb.*index\s(?<shas>\S+)/m.match diff do |matches|
    Dir.chdir(matches[:loc]) do
      travis = TravisBuild.new(matches[:shas], ARGV[0] == "-c")
      travis.log_sorted_by_author_with_travis_status
    end
  end
end
