#!/bin/sh

repo=$1
release=`pwd`

set -e

# buckle up
git submodule foreach \
  "if (pwd | grep -q src/$repo); then" \
  '  sub=`pwd`;' \
  '  git checkout master;' \
  '  git pull;' \
  "  cd $release;" \
  '  git add $sub;' \
  'fi'

./staged_shortlog
