#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 REPO_NAME"
  exit 1
fi

repo=$1
release=`pwd`

set -e

# buckle up
git submodule foreach \
  "if (pwd | grep -q src/$repo); then" \
  '  sub=`pwd`;' \
  '  git checkout master;' \
  '  git pull;' \
  '  git submodule update --init --recursive;' \
  "  cd $release;" \
  '  git add $sub;' \
  'fi'

./staged_shortlog -c
