#!/bin/bash

VBLOB_ADMIN_USER=<%= properties.vblob_node.admin_user   || "vblob_admin" %>
VBLOB_ADMIN_GROUP=<%= properties.vblob_node.admin_group || "admin" %>
VBLOB_ADMIN_PASSWD_HASH=<%= properties.vblob_node.admin_passwd_hash || "" %>

if [ -n "$VBLOB_ADMIN_PASSWD_HASH" ]; then
    # do a mod in addition to the add in order to support password changes
    USER_ARGS="-g $VBLOB_ADMIN_GROUP -p $VBLOB_ADMIN_PASSWD_HASH $VBLOB_ADMIN_USER"
    /usr/sbin/useradd -m -s /bin/bash $USER_ARGS
    /usr/sbin/usermod $USER_ARGS
fi

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/vblob_node
LOG_DIR=/var/vcap/sys/log/vblob_node
PIDFILE=$RUN_DIR/vblob_node.pid
CONF_DIR=/var/vcap/jobs/vblob_node_ng/config
SERV_LOG_DIR=/var/vcap/sys/service-log/vblob
<%
  has_nfs=(properties.vblob_node.nfs_server && properties.vblob_node.nfs_server.address && properties.vblob_node.nfs_server.export_dir)
%>
<% if has_nfs %>
NFS_DIR=<%= properties.vblob_node.nfs_mount_point ? properties.vblob_node.nfs_mount_point : "/var/vcap/vblob_nfs_mount" %>
MT_OPTS="-t nfs"
MT_EXPORT=<%= properties.vblob_node.nfs_server.address %>:<%= properties.vblob_node.nfs_server.export_dir %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "vBlob node"

    sysctl -w net.ipv4.ip_local_port_range="30000 45000"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SERV_LOG_DIR

    echo $$ > $PIDFILE

    /var/vcap/jobs/vblob_node_ng/bin/create_vblob_tmp_dir
    if [ $? -ne 0 ]; then
      echo "failed to create vblob tmp directory"
      exit 1
    fi

    # Enable log aggregation
    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $CONF_DIR
    <% end %>

    <% if has_nfs %>
    mkdir -p $NFS_DIR
    check_mount "$MT_OPTS" "$MT_EXPORT" "$NFS_DIR"
    <% end %>

    (crontab -l | sed /vblob_logrotate/d; cat /var/vcap/jobs/vblob_node_ng/config/vblob_logrotate.cron) | sed /^$/d | crontab

    exec /var/vcap/packages/vblob_node_ng/services/ng/vblob/bin/vblob_node -c /var/vcap/jobs/vblob_node_ng/config/vblob_node.yml >>$LOG_DIR/vblob_node.stdout.log 2>>$LOG_DIR/vblob_node.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE 400 0

    crontab -l | sed /vblob_logrotate/d | crontab

    <% if has_nfs %>
    umount $NFS_DIR
    <% end %>

    ;;

  *)
  echo "Usage: vblob_node_ctl {start|stop}" ;;
esac
exit 0
