#!/bin/bash
STOP_TIMEOUT=<%= properties.vblob_node.instance_stop_timeout || 3 %>
OP=$1
BASE_DIR=$2
LOG_DIR=$3
PIDFILE=$BASE_DIR/service.pid

source /var/vcap/packages/common/utils.sh
exec 1>> $LOG_DIR/$SCRIPT.log
exec 2>> $LOG_DIR/$SCRIPT.err.log

case $OP in
  start)
    BIN_DIR=$4
    NODE_DIR=$5
    # start the instance
    touch $LOG_DIR/vblob.log
    echo $$ >> $PIDFILE
    exec $NODE_DIR/bin/node $BIN_DIR/server.js -f $BASE_DIR/config.json
    ;;

  stop)
    kill_and_wait $PIDFILE $STOP_TIMEOUT 1
    ;;

  status)
    [ -f $PIDFILE ] && [ -e /proc/`head -1 $PIDFILE` ]
    ;;

  *)
    echo "Usage: $0 {start|stop|status}"

    ;;
esac
