#!/bin/bash

JOB_DIR=/var/vcap/jobs/vblob_node_ng
PKG_DIR=/var/vcap/packages/vblob_node_ng
BIN_DIR=/var/vcap/packages

source /var/vcap/packages/vblob_node_ng/common/services/utils.sh

case $1 in

  start)
    setup_warden

    # Copy vblob binaries and configuration files to warden base file system
    install -m 0755 -t $ROOT_DIR/usr/sbin $JOB_DIR/bin/pre_service_start.sh
    install -m 0755 -t $ROOT_DIR/usr/bin   $JOB_DIR/bin/warden_service_ctl
    install -m 0755 -t $ROOT_DIR/usr/bin  /var/vcap/packages/common/utils.sh
    cp -af $BIN_DIR/node/* $ROOT_DIR/usr/
    mkdir -p $ROOT_DIR/var/vcap/packages/vblob
    cp -af $BIN_DIR/vblob/* $ROOT_DIR/var/vcap/packages/vblob/

    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
