#!/bin/bash

JOB_DIR=/var/vcap/jobs/vblob_node_ng
PKG_DIR=/var/vcap/packages/vblob_node_ng
BIN_DIR=/var/vcap/packages

source /var/vcap/packages/vblob_node_ng/common/services/utils.sh

case $1 in

  start)
    setup_warden
    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
