#!/bin/bash

RUN_DIR=/var/vcap/sys/run/vcap_redis
LOG_DIR=/var/vcap/sys/log/vcap_redis
PIDFILE=$RUN_DIR/vcap_redis.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "VCAP Redis"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    echo $$ > $PIDFILE

    exec /var/vcap/packages/redis/bin/redis-server /var/vcap/jobs/vcap_redis/config/vcap_redis.conf

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: vcap_redis_ctl {start|stop}"

    ;;

esac
