#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/atmos_gateway
LOG_DIR=/var/vcap/sys/log/atmos_gateway
PIDFILE=$RUN_DIR/atmos_gateway.pid

JOB_DIR=/var/vcap/jobs/atmos_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Atmos gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/atmos_gateway/services/atmos/bin/atmos_gateway \
         -c $JOB_DIR/config/atmos_gateway.yml \
         >>$LOG_DIR/atmos_gateway.stdout.log \
         2>>$LOG_DIR/atmos_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: atmos_gateway_ctl {start|stop}"

    ;;

esac
