#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/marketplace_gateway
LOG_DIR=/var/vcap/sys/log/marketplace_gateway
PIDFILE=$RUN_DIR/marketplace_gateway.pid
JOB_DIR=/var/vcap/jobs/marketplace_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Marketplace Gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    echo $$ > $PIDFILE

    exec /var/vcap/packages/marketplace/services/marketplace/bin/marketplace_gateway \
         -c $JOB_DIR/config/marketplace_gateway.yml \
         >>$LOG_DIR/marketplace_gateway.stdout.log \
         2>>$LOG_DIR/marketplace_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: marketplace_gateway_ctl {start|stop}"

    ;;

esac
