#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/filesystem_gateway
LOG_DIR=/var/vcap/sys/log/filesystem_gateway
PIDFILE=$RUN_DIR/filesystem_gateway.pid
JOB_DIR=/var/vcap/jobs/filesystem_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Filesystem gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% for backend in properties.filesystem_gateway.backends %>
    mkdir -p <%= backend.mount %>
    mount <%= backend.host %>:<%= backend.export %> <%= backend.mount %>
    <% end %>

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/filesystem_gateway/bin/services/filesystem_gateway \
         -c $JOB_DIR/config/filesystem_gateway.yml \
         >>$LOG_DIR/filesystem_gateway.stdout.log \
         2>>$LOG_DIR/filesystem_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: filesystem_gateway_ctl {start|stop}"

    ;;

esac
