#!/bin/bash
PIDFILE=/store/instance/services.pid
case $1 in
  start)
    for n in `seq 1 100`; do
      if [ -f /tmp/vcap_chown.out ]; then
        break
      fi
      sleep 0.1
    done

    mkdir -p /store/instance/mysql_tmp
    mkdir -p /var/vcap/sys/run
    /var/vcap/packages/mysql/libexec/mysql_warden.server start /store/instance/my.cnf
    head -n 1 /var/vcap/sys/run/mysqld/mysqld.pid > $PIDFILE

    ;;

  stop)
    kill `head -1 $PIDFILE`

    ;;

  *)
    echo "Usage: services_ctl {start|stop}"

    ;;
esac
