#!/bin/bash
case $1 in
  start)
    shift
    version=$1
    # check whether the chown of /store has finished
    for n in `seq 1 100`; do
      if [ -f /tmp/vcap_chown.out ]; then
        break
      fi
      sleep 0.1
    done

    mkdir -p /store/instance/mysql_tmp
    mkdir -p /var/vcap/sys/run

    /var/vcap/packages/mysql${version}/libexec/mysql_warden.server start /store/instance/my.cnf
    ;;

  stop)
    #TODO
    ;;

  status)
    #TODO
    ;;

  *)
    echo "Usage: $0 {start|stop|status}"

    ;;
esac
