#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/redis_node
LOG_DIR=/var/vcap/sys/log/redis_node
SERV_LOG_DIR=/var/vcap/sys/service-log/redis
PIDFILE=$RUN_DIR/redis_node.pid
JOB_DIR=/var/vcap/jobs/redis_node

<%
migration = properties.service_migration
%>

MIG_DIR=<%= (migration && migration.mount_point) ? migration.mount_point : "/var/vcap/services_migration" %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Redis node"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SERV_LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    cp $JOB_DIR/config/logrotate /etc/logrotate.d/vcap-services

    if [ ! -d $MIG_DIR ]; then
      mkdir -p $MIG_DIR
    fi

    chmod +x $JOB_DIR/config/redis_backup
    $JOB_DIR/config/redis_backup start

    exec /var/vcap/packages/redis_node/bin/services/redis_node \
         -c $JOB_DIR/config/redis_node.yml \
         >>$LOG_DIR/redis_node.stdout.log \
         2>>$LOG_DIR/redis_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    chmod +x $JOB_DIR/config/redis_backup
    $JOB_DIR/config/redis_backup stop
    rm /etc/logrotate.d/vcap-services

    ;;

  *)
    echo "Usage: redis_node_ctl {start|stop}"

    ;;

esac
