#!/bin/bash -e
# Cleanup dir once it exceeds threshold (in M)

dir=$1
threshold=$2

if [[ $dir && $threshold && -d $dir ]]; then
  size=`du -ms $dir | cut -f 1`

  if [[ $size && $size -gt $threshold ]]; then
    rm -rf $dir/*
  fi
else
  echo "Usage: $0 <dir> <threshold>"
fi
