#!/bin/bash -e

me=${0##*/}

# Add the third party jars
CLASSPATH=$(JARS=(`find /var/vcap/packages/opentsdb/build/third_party -name '*.jar'`); IFS=:; echo "${JARS[*]}")

# Add TSDB jar and config/logging
CLASSPATH="$CLASSPATH:/var/vcap/jobs/opentsdb/config/opentsdb:/var/vcap/packages/opentsdb/build:/var/vcap/packages/opentsdb/src"

usage() {
  echo >&2 "usage: $me <command> [args]"
  echo 'Valid commands: fsck, import, mkmetric, query, tsd, scan, uid'
  exit 1
}

case $1 in
  (fsck)
    MAINCLASS=Fsck
    ;;
  (import)
    MAINCLASS=TextImporter
    ;;
  (mkmetric)
    shift
    set uid assign metrics "$@"
    MAINCLASS=UidManager
    ;;
  (query)
    MAINCLASS=CliQuery
    ;;
  (tsd)
    MAINCLASS=TSDMain
    ;;
  (scan)
    MAINCLASS=DumpSeries
    ;;
  (uid)
    MAINCLASS=UidManager
    ;;
  (*)
    echo >&2 "$me: error: unknown command '$1'"
    usage
    ;;
esac
shift

exec java -Xmx2048m -ea -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:OnOutOfMemoryError='kill -9 %p' \
 -Dtsd.feature.compactions -classpath "$CLASSPATH" net.opentsdb.tools.$MAINCLASS "$@"