#!/bin/bash -e

export PATH=/var/vcap/packages/ruby_next/bin:$PATH
export PATH=/var/vcap/packages/git/bin:$PATH
RUN_DIR=/var/vcap/sys/run/login
LOG_DIR=/var/vcap/sys/log/login
PIDFILE=$RUN_DIR/vcap_registrar.pid
VCAP_COMMON_PATH=/var/vcap/packages/login/vcap-common

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "VCAP registrar"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    export CONFIG_FILE=/var/vcap/jobs/login/config/vcap_registrar/config.yml

    cd $VCAP_COMMON_PATH
    exec /var/vcap/packages/ruby_next/bin/bundle exec \
         $VCAP_COMMON_PATH/bin/cf-registrar \
         --register-with-router \
         --register-varz-credentials \
         >>$LOG_DIR/vcap_registrar.stdout.log \
         2>>$LOG_DIR/vcap_registrar.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: vcap_registrar_ctl {start|stop}" ;;

esac
exit 0
