#!/bin/bash
<%
migration = properties.service_migration
lifecycle = properties.service_lifecycle
%>
export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/mongodb_node
LOG_DIR=/var/vcap/sys/log/mongodb_node
SERV_LOG_DIR=/var/vcap/sys/service-log/mongodb
PIDFILE=$RUN_DIR/mongodb_node.pid
JOB_DIR=/var/vcap/jobs/mongodb_node
MIG_DIR=<%= migration && migration.mount_point || "/var/vcap/services_migration" %>
<% if lifecycle and lifecycle.nfs_server %>
SNAPSHOT_DIR=<%= lifecycle.mount_point || "/var/vcap/services_snapshot" %>
MT_OPTS="-o noac -t nfs"
MT_EXPORT=<%= lifecycle.nfs_server.address %>:<%= lifecycle.nfs_server.export_dir %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "MongoDB node"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SERV_LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    mkdir -p $MIG_DIR
    <% if lifecycle %>
    mkdir -p $SNAPSHOT_DIR
    check_mount "$MT_OPTS" "$MT_EXPORT" "$SNAPSHOT_DIR"
    <% end %>

    chmod +x $JOB_DIR/config/mongodb_backup
    $JOB_DIR/config/mongodb_backup start

    (crontab -l | sed /mongodb_logrotate/d; cat /var/vcap/jobs/mongodb_node/config/mongodb_logrotate.cron) | sed /^$/d | crontab

    exec /var/vcap/packages/mongodb_node/bin/services/mongodb_node \
         -c $JOB_DIR/config/mongodb_node.yml \
         >>$LOG_DIR/mongodb_node.stdout.log \
         2>>$LOG_DIR/mongodb_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    crontab -l | sed /mongodb_logrotate/d | crontab

    chmod +x $JOB_DIR/config/mongodb_backup
    $JOB_DIR/config/mongodb_backup stop
    <% if lifecycle %>
    umount -l $SNAPSHOT_DIR
    <% end %>

    ;;

  *)
    echo "Usage: mongodb_node_ctl {start|stop}"

    ;;

esac
