#!/bin/bash
export PATH=/var/vcap/packages/ruby/bin:$PATH

INDEX=$2
RUN_DIR=/var/vcap/sys/run/mongodb_node
LOG_DIR=/var/vcap/sys/log/mongodb_node
PIDFILE=$RUN_DIR/mongodb_worker_$INDEX.pid
JOB_DIR=/var/vcap/jobs/mongodb_node

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "MongoDB worker"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    export CLOUD_FOUNDRY_CONFIG_PATH=$JOB_DIR/config/
    export PIDFILE=$PIDFILE

    exec /var/vcap/packages/mongodb_node/services/mongodb/bin/mongodb_worker \
         >>$LOG_DIR/mongodb_worker_$INDEX.stdout.log \
         2>>$LOG_DIR/mongodb_worker_$INDEX.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: mongodb_worker_ctl {start|stop}"

    ;;

esac
