#!/bin/bash

JOB_DIR=/var/vcap/jobs/mongodb_node
PKG_DIR=/var/vcap/packages/mongodb_node
BIN_DIR=/var/vcap/packages/mongodb18/bin

source /var/vcap/packages/mongodb_node/common/warden_service.sh

case $1 in

  start)
    setup_warden

    # Copy mongodb binaries and configuration files to warden base file system
    install -m 0755 -t $ROOT_DIR/usr/bin $JOB_DIR/bin/mongod_startup.sh $BIN_DIR/*
    install -m 0644 -t $ROOT_DIR/etc     $JOB_DIR/config/mongodb.conf
    install -m 0644 -t $ROOT_DIR/etc/init    $JOB_DIR/config/services.conf

    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
