#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/mongodb_gateway
LOG_DIR=/var/vcap/sys/log/mongodb_gateway
PIDFILE=$RUN_DIR/mongodb_gateway.pid

JOB_DIR=/var/vcap/jobs/mongodb_gateway

<%
lifecycle = properties.service_lifecycle
%>

<% if lifecycle %>
SNAPSHOT_DIR=<%= lifecycle.mount_point || "/var/vcap/services_snapshot" %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "MongoDB gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    <% if lifecycle %>
    if [ ! -d $SNAPSHOT_DIR ]; then
      mkdir -p $SNAPSHOT_DIR
    fi
    <% end %>

    <% if lifecycle && lifecycle.nfs_server %>
    mount -t nfs <%= lifecycle.nfs_server.address %>:<%= lifecycle.nfs_server.export_dir %> $SNAPSHOT_DIR
    <% end %>

    exec /var/vcap/packages/mongodb_gateway/bin/services/mongodb_gateway \
         -c $JOB_DIR/config/mongodb_gateway.yml \
         >>$LOG_DIR/mongodb_gateway.stdout.log \
         2>>$LOG_DIR/mongodb_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE
    <% if lifecycle && lifecycle.nfs_server %>
    umount $SNAPSHOT_DIR
    <% end %>

    ;;

  *)
    echo "Usage: mongodb_gateway_ctl {start|stop}"

    ;;

esac
