#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/memcached_node
LOG_DIR=/var/vcap/sys/log/memcached_node
SERV_LOG_DIR=/var/vcap/sys/service-log/memcached
PIDFILE=$RUN_DIR/memcached_node.pid
JOB_DIR=/var/vcap/jobs/memcached_node

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "memcached node"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SERV_LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    cp $JOB_DIR/config/logrotate /etc/logrotate.d/vcap-services

    exec /var/vcap/packages/memcached_node/bin/services/memcached_node \
         -c $JOB_DIR/config/memcached_node.yml \
         >>$LOG_DIR/memcached_node.stdout.log \
         2>>$LOG_DIR/memcached_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE
    rm /etc/logrotate.d/vcap-services

    ;;

  *)
    echo "Usage: memcached_node_ctl {start|stop}"

    ;;

esac
