#!/bin/bash
export PATH=/var/vcap/packages/ruby/bin:$PATH

INDEX=$2
RUN_DIR=/var/vcap/sys/run/redis_node
LOG_DIR=/var/vcap/sys/log/redis_node
PIDFILE=$RUN_DIR/redis_worker_$INDEX.pid
JOB_DIR=/var/vcap/jobs/redis_node_ng

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Redis worker"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    export CLOUD_FOUNDRY_CONFIG_PATH=$JOB_DIR/config/
    export PIDFILE=$PIDFILE

    exec /var/vcap/packages/redis_node_ng/services/ng/redis/bin/redis_worker \
         >>$LOG_DIR/redis_worker_$INDEX.stdout.log \
         2>>$LOG_DIR/redis_worker_$INDEX.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: redis_worker_ctl {start|stop}"

    ;;

esac
