#!/bin/bash

JOB_DIR=/var/vcap/jobs/redis_node_ng
PKG_DIR=/var/vcap/packages/redis_node_ng

REDIS22_BIN_DIR=/var/vcap/packages/redis22/bin
REDIS24_BIN_DIR=/var/vcap/packages/redis24/bin
REDIS26_BIN_DIR=/var/vcap/packages/redis26/bin


source /var/vcap/packages/redis_node_ng/common/services/utils.sh

case $1 in

  start)
    setup_warden

    mkdir -p $ROOT_DIR/usr/share/redis/redis-2.2
    mkdir -p $ROOT_DIR/usr/share/redis/redis-2.4
    mkdir -p $ROOT_DIR/usr/share/redis/redis-2.6

    # Copy redis binaries and configuration files to warden base file system
    install -m 0755 -t $ROOT_DIR/usr/bin  $JOB_DIR/bin/redis_startup.sh
    install -m 0755 -t $ROOT_DIR/usr/share/redis/redis-2.2 $REDIS22_BIN_DIR/*
    install -m 0755 -t $ROOT_DIR/usr/share/redis/redis-2.4 $REDIS24_BIN_DIR/*
    install -m 0755 -t $ROOT_DIR/usr/share/redis/redis-2.6 $REDIS26_BIN_DIR/*
    install -m 0644 -t $ROOT_DIR/etc/init $JOB_DIR/config/services.conf

    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
