#!/bin/bash
<%
node = properties.redis_node
%>
JOB_DIR=/var/vcap/jobs/redis_node_ng
PKG_DIR=/var/vcap/packages/redis_node_ng

REDIS22_BIN_DIR=/var/vcap/packages/redis22/bin
REDIS24_BIN_DIR=/var/vcap/packages/redis24/bin
REDIS26_BIN_DIR=/var/vcap/packages/redis26/bin


SERVICE_NAME="redis"
SOCKET_FILE=<%= node.warden_socket_path || "/tmp/warden.sock" %>
source /var/vcap/packages/redis_node_ng/common/services/utils.sh

case $1 in

  start)
    setup_warden
    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
