update:
  canaries: 0

jobs:
  - name: loggregator_z1
    instances: 1

  - name: loggregator_z2
    instances: 1

  - name: loggregator_trafficcontroller_z1
    instances: 1

  - name: loggregator_trafficcontroller_z2
    instances: 1

  - name: logs_z1
    instances: 0

  - name: logs_z2
    instances: 0

  - name: router_z2
    instances: 1

  - name: runner_z1
    instances: 1

  - name: runner_z2
    instances: 1

  - name: hm9000_z2
    instances: 1

  - name: etcd_z1
    instances: 1

  - name: etcd_z2
    instances: 1

properties:
  ssl:
    skip_cert_verify: true
