---
meta:

properties:
  databases:
    collect_statement_statistics: true
  dea_next:
    evacuation_bail_out_time_in_seconds: 0
    memory_mb: 8192
    disk_mb: 32768
    disk_overcommit_factor: 3
    kernel_network_tuning_enabled: false
  uaa:
    require_https: false
    zones:
      internal:
        hostnames:
        - uaa.service.cf.internal

jobs:
  - name: api_z1
    properties:
      consul:
        agent:
          services:
            cloud_controller_ng: {}
