#!/bin/bash

COMPONENT=vcap-web

SRS_ADMIN_USER=<%= properties.rabbitmq_srs.admin_user || "srs_admin" %>
SRS_ADMIN_GROUP=<%= properties.rabbitmq_srs.admin_group || "admin" %>
SRS_ADMIN_PASSWD_HASH=<%= properties.rabbitmq_srs.admin_passwd_hash || "" %>

PIDFILE=/var/vcap/sys/run/rabbitmq_srs_vcap_web.pid
COMPONENT_DIR=/var/vcap/store/rabbitmq_srs/$COMPONENT

cd /var/vcap/packages/rabbitmq_srs
cd $(etc/component-gem $COMPONENT)

export PATH=/var/vcap/packages/ruby/bin:$PATH
export RUBYLIB=$PWD/lib:$RUBYLIB
export SRS_CONFIG=$(readlink -f $(dirname $0)/../config/srs-config.json)

source /var/vcap/packages/common/utils.sh

case $1 in
  start)
    pid_guard $PIDFILE "Rabbit gateway"
    echo $$ > $PIDFILE

    if [ -n "$SRS_ADMIN_PASSWD_HASH" ]; then
      # do a mod in addition to the add in order to support password changes
      USER_ARGS="-g $SRS_ADMIN_GROUP -p $SRS_ADMIN_PASSWD_HASH $SRS_ADMIN_USER"
      /usr/sbin/useradd -m -s /bin/bash $USER_ARGS
      /usr/sbin/usermod $USER_ARGS
    fi

    if ! [ -d $COMPONENT_DIR ] ; then
      mkdir -p $(dirname $COMPONENT_DIR)
      bundle exec bin/$COMPONENT setup --http-port=80 $COMPONENT_DIR
    fi

    bundle exec bin/$COMPONENT start $COMPONENT_DIR
    cp $COMPONENT_DIR/$COMPONENT.pid $PIDFILE

    ;;

  stop)
    bundle exec bin/$COMPONENT stop $COMPONENT_DIR
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: $(basename $0) {start|stop}"

    ;;

esac
