#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/rabbit_gateway
LOG_DIR=/var/vcap/sys/log/rabbit_gateway
JOB_DIR=/var/vcap/jobs/rabbit_gateway

PIDFILE=$RUN_DIR/rabbit_gateway.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Rabbit gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    echo $$ > $PIDFILE
    exec /var/vcap/packages/rabbit_gateway/services/rabbit/bin/rabbit_gateway \
        -c $JOB_DIR/config/rabbit_gateway.yml \
        >>$LOG_DIR/rabbit_gateway.stdout.log \
        2>>$LOG_DIR/rabbit_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: rabbit_gateway_ctl {start|stop}"

    ;;

esac
