#!/bin/bash
set -o errexit

RUN_DIR=/var/vcap/sys/run/warden
LOG_DIR=/var/vcap/sys/log/warden
WARDEN_DATA_ROOT=/var/vcap/data/warden
WARDEN_CONF_DIR=/var/vcap/jobs/stager_next/config
PIDFILE=$RUN_DIR/warden.pid
FIRSTRUN_PATH=$RUN_DIR/firstrun

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Warden"

    mkdir -p $WARDEN_DATA_ROOT
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    echo $$ > $PIDFILE

    export PATH=/var/vcap/packages/ruby/bin:$PATH

    cd /var/vcap/packages/warden/warden

    if [ ! -e $FIRSTRUN_PATH ]; then
      touch $FIRSTRUN_PATH

      # Unzip base chroot from stemcell
      CHROOT_BASE=$WARDEN_DATA_ROOT/rootfs
      mkdir -p $CHROOT_BASE
      tar -C $CHROOT_BASE -zxf /var/vcap/stemcell_base.tar.gz

      # Configure it to our liking, as well as compile helper binaries
      env SKIP_DEBOOTSTRAP=true SKIP_APT=true bundle exec rake setup[$CHROOT_BASE]
    fi

    exec bundle exec \
         rake warden:start[$WARDEN_CONF_DIR/warden.yml] \
         >>$LOG_DIR/warden.stdout.log \
         2>>$LOG_DIR/warden.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"

    ;;

esac
