#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/memcached_gateway
LOG_DIR=/var/vcap/sys/log/memcached_gateway
JOB_DIR=/var/vcap/jobs/memcached_gateway

PIDFILE=$RUN_DIR/memcached_gateway.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "memcached gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/memcached_gateway/services/ng/memcached/bin/memcached_gateway \
         -c $JOB_DIR/config/memcached_gateway.yml \
         >>$LOG_DIR/memcached_gateway.stdout.log \
         2>>$LOG_DIR/memcached_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: memcached_gateway_ctl {start|stop}"

    ;;

esac
