#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH
RUN_DIR=/var/vcap/sys/run/stager
LOG_DIR=/var/vcap/sys/log/stager
JOB_DIR=/var/vcap/jobs/stager
GEM_CACHE_DIR=/var/vcap/data/stager/package_cache/ruby
TMP_DIR=/var/vcap/data/stager/tmp
PIDFILE=$RUN_DIR/stager.pid

<% if properties.env %>
<% if properties.env.http_proxy %>
export HTTP_PROXY='<%= properties.env.http_proxy %>'
export http_proxy='<%= properties.env.http_proxy %>'
<% end %>
<% if properties.env.https_proxy %>
export HTTPS_PROXY='<%= properties.env.https_proxy %>'
export https_proxy='<%= properties.env.https_proxy %>'
<% end %>
<% if properties.env.no_proxy %>
export NO_PROXY='<%= properties.env.no_proxy %>'
export no_proxy='<%= properties.env.no_proxy %>'
<% end %>
<% end %>

export C_INCLUDE_PATH=/var/vcap/packages/mysqlclient/include/mysql:/var/vcap/packages/sqlite/include:/var/vcap/packages/libpq/include:/var/vcap/packages/imagemagick/include/ImageMagick:$C_INCLUDE_PATH
export LIBRARY_PATH=/var/vcap/packages/mysqlclient/lib/mysql:/var/vcap/packages/sqlite/lib:/var/vcap/packages/libpq/lib:/var/vcap/packages/imagemagick/lib:$LIBRARY_PATH
export PATH=/var/vcap/packages/dea_node08/bin:/var/vcap/packages/imagemagick/bin:/var/vcap/packages/git/bin:$PATH
export LANG=en_US.UTF-8
export PLATFORM_CONFIG=$JOB_DIR/config/platform.yml

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Stager"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $TMP_DIR

    chown vcap:vcap $RUN_DIR
    chown vcap:vcap $LOG_DIR
    chown vcap:vcap $TMP_DIR

    echo $$ > $PIDFILE
    chown vcap:vcap $PIDFILE

    mkdir -p $GEM_CACHE_DIR

    # Remove unused npm cache directory
    NPM_OLD_CACHE=$GEM_CACHE_DIR/npm_cache/installed
    if [ -d $NPM_OLD_CACHE ]; then
      echo "Found old npm cache directory, deleting..."
      rm -rf $NPM_OLD_CACHE
    fi

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    # Migrate blessed gems to their new home
    mkdir -p $GEM_CACHE_DIR/blessed_gems
    if [ -d $GEM_CACHE_DIR/1.8/blessed_gems ]; then
      mv -n $GEM_CACHE_DIR/1.8/blessed_gems/* $GEM_CACHE_DIR/blessed_gems
    fi
    if [ -d $GEM_CACHE_DIR/1.9.1/blessed_gems ]; then
      mv -n $GEM_CACHE_DIR/1.9.1/blessed_gems/* $GEM_CACHE_DIR/blessed_gems
    fi
    rm -rf $GEM_CACHE_DIR/1.8/blessed_gems
    rm -rf $GEM_CACHE_DIR/1.9.1/blessed_gems

    # Migrate cached gems to their new home
    mkdir -p $GEM_CACHE_DIR/1.8.7p357
    if [ -d $GEM_CACHE_DIR/1.8 ]; then
      mv -n $GEM_CACHE_DIR/1.8/* $GEM_CACHE_DIR/1.8.7p357
    fi
    mkdir -p $GEM_CACHE_DIR/1.9.2p180
    if [ -d $GEM_CACHE_DIR/1.9.1 ]; then
      mv -n $GEM_CACHE_DIR/1.9.1/* $GEM_CACHE_DIR/1.9.2p180
    fi
    rm -rf $GEM_CACHE_DIR/1.8
    rm -rf $GEM_CACHE_DIR/1.9.1

    # Seed the staging cache
    # TODO make dea_seed use a single blessed_gems dir and correct version numbers for easier copy
    cp -an /var/vcap/packages/dea_seed/gem_cache/1.8/gem_cache/* $GEM_CACHE_DIR/1.8.7p357/gem_cache
    cp -an /var/vcap/packages/dea_seed/gem_cache/1.9.1/gem_cache/* $GEM_CACHE_DIR/1.9.2p180/gem_cache
    cp -an /var/vcap/packages/dea_seed/gem_cache/1.9.1/blessed_gems/* $GEM_CACHE_DIR/blessed_gems

    chown -R vcap:vcap $GEM_CACHE_DIR

    /var/vcap/packages/ruby/bin/ruby /var/vcap/packages/stager/bin/create_secure_users.rb

    # Set up sudoers for stager.
    install_sudoers "$JOB_DIR/config/sudoers" /etc/sudoers.d/stager
    file_must_include /etc/sudoers '#includedir /etc/sudoers.d'

    exec chpst -u vcap:vcap /var/vcap/packages/ruby/bin/ruby \
         /var/vcap/packages/stager/bin/stager \
         -c $JOB_DIR/config/stager.yml \
         >>$LOG_DIR/stager.stdout.log \
         2>>$LOG_DIR/stager.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: stager_ctl {start|stop} {worker_index}"

    ;;

esac
