#!/bin/bash

RUN_DIR=/var/vcap/sys/run/log_server
LOG_DIR=/var/vcap/sys/log/log_server
PIDFILE=$RUN_DIR/log_server.pid
JOB_DIR=/var/vcap/jobs/log_server

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "LOG_SERVER"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    # Configure the core file location
    mkdir -p /var/vcap/sys/cores
    chown vcap:vcap /var/vcap/sys/cores
    echo /var/vcap/sys/cores/core-%e-%s-%p-%t > /proc/sys/kernel/core_pattern

    ulimit -c unlimited

    source /var/vcap/packages/log_server/keys.sh
    exec /var/vcap/packages/log_server/bin/logplex \
         >> $LOG_DIR/log_server.stdout.log \
         2>> $LOG_DIR/log_server.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: log_server_ctl {start|stop}"

    ;;

esac

