#!/bin/bash -e
# Cleanup dir once it exceeds threshold (in M)

dir=$1
threshold=$2
savedfile="saved_logs.tar"

if [[ $dir && $threshold && -d $dir ]]; then
  size=`du -ms $dir | cut -f 1`

  if [[ $size && $size -gt $threshold ]]; then
    if [[ -f $dir/$savedfile ]]; then
      rm $dir/$savedfile
    fi
    cd $dir
    tar -pczf ../$savedfile ./
    rm -rf $dir/*
    mv $dir/../$savedfile $dir/$savedfile
  fi
else
  echo "Usage: $0 <dir> <threshold>"
fi
