#!/bin/bash -e

HBASE_BIN="/var/vcap/packages/hbase/bin"
RUN_DIR="/var/vcap/sys/run/hbase_slave"
LOG_DIR="/var/vcap/sys/log/hbase_slave"

PIDFILE="${RUN_DIR}/hbase-vcap-regionserver.pid"

export JAVA_HOME="/var/vcap/packages/dea_jvm"
export HBASE_HEAPSIZE=<%= properties.hbase_slave.hbase_regionserver.heap_size %>
export HBASE_IDENT_STRING="vcap"
export HBASE_PID_DIR=$RUN_DIR
export HBASE_LOG_DIR=$LOG_DIR
export HBASE_CONF_DIR="/var/vcap/jobs/hbase_slave/config/hbase"
export HADOOP_HOME="/var/vcap/packages/hadoop"

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    # start-hbase.sh has its own pid guard,
    # we use ours for consistency anyway
    pid_guard $PIDFILE "hbase_regionserver"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    . ${HBASE_BIN}/hbase-config.sh
    errCode=$?
    if [ $errCode -ne 0 ]
    then
      exit $errCode
    fi

    exec chpst -u vcap:vcap ${HBASE_BIN}/hbase-daemon.sh --config "${HBASE_CONF_DIR}" start regionserver \
         >>$LOG_DIR/hbase_regionserver-start.stdout.log \
         2>>$LOG_DIR/hbase_regionserver-start.stderr.log

    ;;

  stop)

    exec chpst -u vcap:vcap ${HBASE_BIN}/hbase-daemon.sh --config "${HBASE_CONF_DIR}" stop regionserver \
         >>$LOG_DIR/hbase_regionserver-start.stdout.log \
         2>>$LOG_DIR/hbase_regionserver-start.stderr.log

    ;;

  *)
    echo "Usage: hbase_ctl {start|stop}"

    ;;

esac
