#!/bin/bash
STOP_TIMEOUT=<%= properties.memcached_node.instance_stop_timeout || 3 %>
OP=$1
shift
BASE_DIR=$1
shift
LOG_DIR=$1
shift
COMMON_DIR=$1
shift
PIDFILE=$BASE_DIR/service.pid

source $COMMON_DIR/bin/utils.sh

case $OP in
  start)
    BIN_DIR=$1
    shift
    ARGS=$*
    echo $$ >> $PIDFILE
    exec /sbin/start-stop-daemon --start --quiet --chuid vcap --exec $BIN_DIR/bin/memcached -- $ARGS
    ;;

  stop)
    kill_and_wait $PIDFILE $STOP_TIMEOUT 1
    ;;

  status)
    [ -f $PIDFILE ] && [ -e /proc/`head -1 $PIDFILE` ]
    ;;

  *)
    echo "Usage: $0 {start|stop|status}"

    ;;
esac
