#!/bin/bash -e

export PATH=/var/vcap/packages/dea_jvm/bin:$PATH
RUN_DIR=/var/vcap/sys/run/dashboard
LOG_DIR=/var/vcap/sys/log/dashboard
PIDFILE=$RUN_DIR/dashboard.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Dashboard"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    # We want to keep packages pristine, since tomcat is modified in place we stage it elsewhere.
    rm -rf /var/vcap/data/dashboard
    mkdir -p /var/vcap/data/dashboard
    cp -a /var/vcap/packages/dashboard/tomcat /var/vcap/data/dashboard
    cp -a /var/vcap/jobs/dashboard/config/tomcat/* /var/vcap/data/dashboard/tomcat/conf/

    export CATALINA_OPTS='-Dconfig=file:///var/vcap/jobs/dashboard/config/dashboard/dashboard.properties'

    cd /var/vcap/data/dashboard

    exec tomcat/bin/catalina.sh run

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: dashboard_ctl {start|stop}"

    ;;

esac
