#!/bin/bash

DAYLIMIT_NG_BIN=/var/vcap/packages/daylimit/daylimit/bin/daylimit
RUN_DIR=/var/vcap/sys/run/daylimit
JOB_DIR=/var/vcap/jobs/rabbit_node_ng
LOG_DIR=/var/vcap/sys/log/daylimit
PIDFILE=${RUN_DIR}/daylimit.pid

source /var/vcap/packages/common/utils.sh
export PATH=/var/vcap/packages/ruby/bin:$PATH
# Used in warden client
export HOME=/var/vcap

case $1 in

  start)
    mkdir -p ${RUN_DIR}
    mkdir -p ${LOG_DIR}
    echo $$ > ${PIDFILE}
    exec ${DAYLIMIT_NG_BIN} -c ${JOB_DIR}/config/daylimit.yml >> ${LOG_DIR}/daylimit.stdout.log 2>>${LOG_DIR}/daylimit.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: daylimit_ctl {start|stop}"
    ;;

esac
