#!/bin/bash
LOGDIR=/store/log
INSDIR=/store/instance
PIDFILE=${INSDIR}/service.pid
STOP_TIMEOUT=<%= properties.rabbit_node.instance_stop_timeout || 3 %>

source /usr/bin/utils.sh
exec 1>> ${LOGDIR}/${SCRIPT}.log
exec 2>> ${LOGDIR}/${SCRIPT}.err.log

case $1 in
  start)
    shift

    version=$1
    shift
    export ERLANG_HOME=/var/vcap/packages/erlang
    export PATH=/var/vcap/packages/erlang/bin:$PATH
    export HOME=${INSDIR}
    export RABBITMQ_NODENAME="$1@localhost"
    export RABBITMQ_NODE_PORT=10001
    export RABBITMQ_BASE=${INSDIR}
    export RABBITMQ_LOG_BASE=${LOGDIR}
    export RABBITMQ_MNESIA_DIR=${INSDIR}/mnesia
    export RABBITMQ_PLUGINS_EXPAND_DIR=${INSDIR}/plugins
    export RABBITMQ_CONFIG_FILE=${INSDIR}/config/rabbitmq
    export RABBITMQ_ENABLED_PLUGINS_FILE=${INSDIR}/config/enabled_plugins
    export RABBITMQ_SERVER_START_ARGS="-smp disable"
    export RABBITMQ_CONSOLE_LOG=reuse
    export ERL_CRASH_DUMP="/dev/null"
    export ERL_CRASH_DUMP_SECONDS="1"
    echo $$ >> $PIDFILE
    exec /sbin/start-stop-daemon --start --quiet --chuid vcap --exec /var/vcap/packages/rabbitmq-${version}/sbin/rabbitmq-server >${LOGDIR}/rabbitmq_stdout.log 2>${LOGDIR}/rabbitmq_stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE $STOP_TIMEOUT 1
    ;;

  status)
    [ -f $PIDFILE ] && [ -e /proc/`head -1 $PIDFILE` ]
    ;;

  *)
    echo "Usage: $0 {start|stop|status}"

    ;;
esac
