#!/bin/bash
<%
node = properties.rabbit_node
%>

JOB_DIR=/var/vcap/jobs/rabbit_node_ng
PKG_DIR=/var/vcap/packages/rabbit_node_ng
USE_LOOP_DEVICE=true

SERVICE_NAME="rabbit"
SOCKET_FILE=<%= node.warden_socket_path || "/tmp/warden.sock" %>
source /var/vcap/packages/rabbit_node_ng/common/services/utils.sh

case $1 in

  start)
    setup_warden ${USE_LOOP_DEVICE}
    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
