#!/bin/bash
PIDFILE=/store/instance/services.pid
case $1 in
  start)
    for n in `seq 1 100`; do
      if [ -f /tmp/vcap_chown.out ]; then
        break
      fi
      sleep 0.1
    done

    touch /store/log/mongodb.log
    mkdir -p /store/instance/data
    echo "$$" > $PIDFILE
    exec /usr/bin/mongod --config /etc/mongodb.conf

    ;;

  stop)
    kill `head -1 $PIDFILE`

    ;;

  *)
    echo "Usage: services_ctl {start|stop}"

    ;;
esac
