#!/bin/bash
PIDFILE=/store/instance/services.pid
case $1 in
  start)
    shift
    for n in `seq 1 100`; do
      if [ -f /tmp/vcap_chown.out ]; then
        break
      fi
      sleep 0.1
    done

    touch /store/log/mongodb.log
    mkdir -p /store/instance/data

    # mongod_startup.sh 1.8
    # mongod_startup.sh 1.8 --journal
    # mongod_startup.sh 2.0
    # mongod_startup.sh 2.0 --nojournal
    version=$1
    shift
    args=$*
    echo "$$" > $PIDFILE
    exec start-stop-daemon --start --quiet --chuid vcap --exec /usr/share/mongodb/mongodb-$version/mongod -- $args --config /etc/mongodb.conf

    ;;

  stop)
    kill `head -1 $PIDFILE`

    ;;

  *)
    echo "Usage: services_ctl {start|stop}"

    ;;
esac
