#!/bin/bash

JOB_DIR=/var/vcap/jobs/mongodb_node_ng
PKG_DIR=/var/vcap/packages/mongodb_node_ng
BIN_MONGO_1dot8_DIR=/var/vcap/packages/mongodb18/bin
BIN_MONGO_2dot0_DIR=/var/vcap/packages/mongodb20/bin
BIN_MONGO_PROXY_DIR=/var/vcap/packages/mongodb_proxy/bin

source /var/vcap/packages/mongodb_node_ng/common/services/utils.sh

case $1 in

  start)
    setup_warden

    mkdir -p $ROOT_DIR/usr/share/mongodb/mongodb-1.8
    mkdir -p $ROOT_DIR/usr/share/mongodb/mongodb-2.0
    mkdir -p $ROOT_DIR/usr/share/mongodb/mongodb_proxy

    # Copy mongodb binaries and configuration files to warden base file system
    install -m 0755 -t $ROOT_DIR/usr/bin $JOB_DIR/bin/mongod_startup.sh
    install -m 0755 -t $ROOT_DIR/usr/share/mongodb/mongodb-1.8 $BIN_MONGO_1dot8_DIR/*
    install -m 0755 -t $ROOT_DIR/usr/share/mongodb/mongodb-2.0 $BIN_MONGO_2dot0_DIR/*
    install -m 0755 -t $ROOT_DIR/usr/share/mongodb/mongodb_proxy $BIN_MONGO_PROXY_DIR/*
    install -m 0644 -t $ROOT_DIR/etc     $JOB_DIR/config/mongodb.conf
    install -m 0644 -t $ROOT_DIR/etc     $JOB_DIR/config/mongodb_proxy.yml
    install -m 0755 -t $ROOT_DIR/usr/sbin $JOB_DIR/bin/pre_service_start.sh

    start_warden
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
