#!/bin/bash

RUN_DIR=/var/vcap/sys/run/warden
LOG_DIR=/var/vcap/sys/log/warden
JOB_DIR=/var/vcap/jobs/vblob_node
WARDEN_CONF_DIR=/var/vcap/jobs/vblob_node/config
PIDFILE=$RUN_DIR/warden.pid
WARDEN_SOURCE_DIR=/var/vcap/packages/vblob_node/warden
NODE_BIN_DIR=/var/vcap/packages/node/
VBLOB_DIR=/var/vcap/packages/vblob/
WARDEN_ROOT_DIR=/var/vcap/packages/vblob_node/warden/root/linux/base/rootfs/

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Warden"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    echo $$ > $PIDFILE

    cd /var/vcap/packages/vblob_node/warden

    export PATH=/var/vcap/packages/ruby/bin:$PATH

    # Copy node.js binaries and vblob server to warden base file system
    cp -rf $NODE_BIN_DIR/* $WARDEN_ROOT_DIR/usr
    cp -rf $JOB_DIR/bin/vblob_startup.sh $WARDEN_ROOT_DIR/usr/bin
    chmod 755 $WARDEN_ROOT_DIR/usr/bin/vblob_startup.sh
    mkdir -p $WARDEN_ROOT_DIR/$VBLOB_DIR
    cp -rf $VBLOB_DIR/* $WARDEN_ROOT_DIR/$VBLOB_DIR
    cp -rf $JOB_DIR/config/services.conf $WARDEN_ROOT_DIR/etc/init/services.conf
    chmod 0644 $WARDEN_ROOT_DIR/etc/init/services.conf

    exec /var/vcap/packages/ruby/bin/bundle exec \
         rake warden:start[$WARDEN_CONF_DIR/warden.yml] \
         >>$LOG_DIR/warden.stdout.log \
         2>>$LOG_DIR/warden.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"

    ;;

esac
