#!/bin/bash

JOB_NAME=vblob_node
JOB_DIR=/var/vcap/jobs/vblob_node
PIDFILE=/var/vcap/sys/run/warden/warden.pid
NODE_BIN_DIR=/var/vcap/packages/node
VBLOB_DIR=/var/vcap/packages/vblob/
WARDEN_ROOT_DIR=/var/vcap/packages/vblob_node/warden/root/linux/base/rootfs/
VBLOB_STARTUP=$WARDEN_ROOT_DIR/usr/bin/vblob_startup.sh

source /var/vcap/packages/common/utils.sh
source /var/vcap/packages/vblob_node/common/warden_service.sh

case $1 in

  start)
    pid_guard $PIDFILE "Warden"

    src=("$NODE_BIN_DIR" "$JOB_DIR/bin/vblob_startup.sh" "$VBLOB_DIR" \
         "$JOB_DIR/config/services.conf")
    dest=("$WARDEN_ROOT_DIR/usr" "$WARDEN_ROOT_DIR/usr/bin" "$WARDEN_ROOT_DIR/$VBLOB_DIR" \
          "$WARDEN_ROOT_DIR/etc/init")

    prepare_warden $JOB_NAME $src $dest

    start_warden $JOB_NAME $VBLOB_STARTUP

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"

    ;;

esac
