#!/bin/bash
export PATH=/var/vcap/packages/ruby/bin:$PATH

INDEX=$2
RUN_DIR=/var/vcap/sys/run/postgresql_node
LOG_DIR=/var/vcap/sys/log/postgresql_node
PIDFILE=$RUN_DIR/postgresql_worker_$INDEX.pid
JOB_DIR=/var/vcap/jobs/postgresql_node

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Postgresql worker"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    export CLOUD_FOUNDRY_CONFIG_PATH=$JOB_DIR/config/
    export PIDFILE=$PIDFILE

    exec /var/vcap/packages/postgresql_node/services/postgresql/bin/postgresql_worker \
         >>$LOG_DIR/postgresql_worker_$INDEX.stdout.log \
         2>>$LOG_DIR/postgresql_worker_$INDEX.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: postgresql_worker_ctl {start|stop}"
    ;;
esac
