#!/bin/bash
# vim: set ft=sh

set -e -x

pidfile=/var/vcap/sys/run/gorouter/gorouter.pid
logfile=/var/vcap/sys/log/gorouter/drain.log

mkdir -p $(dirname $logfile)

if [ ! -f $pidfile ]; then
  echo "$(date): pidfile does not exist" >> $logfile
  echo 0
  exit 0
fi

pid=$(cat $pidfile)

if kill -USR1 $pid; then
  echo "$(date): triggering drain" >> $logfile
  echo -5
else
  echo "$(date): gorouter exited" >> $logfile
  echo 0
fi
