name: cf-acceptance-tests

director_uuid: (( merge ))

releases:
  - name: cf
    version: latest

networks:
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - (( Resources.SecurityGroupName.Internal ))
      subnet: (( Resources.Subnet.CFZ1 ))

resource_pools:
  - name: small_errand
    network: default
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      availability_zone: (( Resources.SubnetAvailabilityZone.CFZ1 ))
      instance_type: m3.medium

compilation:
  network: default
  workers: 6
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: (( Resources.SubnetAvailabilityZone.CFZ1 ))
    instance_type: c1.medium

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

jobs:
- name: cf_acceptance_tests
  templates:
    - name: acceptance-tests
      release: cf
  lifecycle: errand
  instances: 1
  networks:
    - name: default
  resource_pool: small_errand

properties:
  domain: (( merge ))
  app_domains: (( merge || [] ))
  acceptance_tests:
    api:  (( "api." properties.domain ))
    apps_domain: (( properties.app_domains.[0] || properties.domain ))
    admin_user: (( cloud_controller_admin_credentials.username ))
    admin_password: (( cloud_controller_admin_credentials.password ))
    skip_ssl_validation: (( properties.ssl.skip_cert_verify ))
    ginkgo_opts: ~ # use default in job spec unless intentionally overridden in stub
    diego: false
    include_sso: ~ # use default in job spec unless intentionally overridden in stub
  ssl: (( merge ))

Resources: (( merge ))

cloud_controller_admin_credentials: (( merge ))

