meta:
  releases: ~
  environment: ~
  networks: ~

  openstack: (( merge ))

  stemcell:
    name: bosh-openstack-kvm-ubuntu-lucid-go_agent
    version: latest

  floating_static_ips: (( merge ))

networks: (( merge ))

properties:
  logger_endpoint:
    port: 4443

  loggregator:
    blacklisted_syslog_ranges: (( merge || [] ))

  cc: (( merge ))

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    clients: (( merge ))

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

  dea_next:
    deny_networks: (( merge || nil ))
    allow_networks: (( merge || nil ))

  nats:
    address: (( jobs.nats_z1.networks.cf1.static_ips.[0] ))

  ccdb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: ccdb
      tag: cc
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: (( merge ))
      tag: admin

  uaadb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: (( merge ))
      tag: admin

  databases:
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: (( merge ))
      - tag: admin
        name: uaaadmin
        password: (( merge ))

    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

compilation:
  cloud_properties:
    instance_type: m1.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

  - name: small_z2
    cloud_properties:
      instance_type: m1.small

  - name: medium_z1
    cloud_properties:
      instance_type: m1.medium

  - name: medium_z2
    cloud_properties:
      instance_type: m1.medium

  - name: large_z1
    cloud_properties:
      instance_type: m1.large

  - name: large_z2
    cloud_properties:
      instance_type: m1.large

  - name: runner_z1
    cloud_properties:
      instance_type: m1.large

  - name: runner_z2
    cloud_properties:
      instance_type: m1.large

  - name: router_z1
    cloud_properties:
      instance_type: m1.medium

  - name: router_z2
    cloud_properties:
      instance_type: m1.medium

# This config is for the simplest Openstack config using just one AZ.
# All values for "z2" and network "cf2" are set to null. They'll end up
# in the final 'spiff merge' manifest with zero instances.
jobs:
  - name: ha_proxy_z1
    instances: 1
    networks:
      - name: floating
        static_ips: (( meta.floating_static_ips ))
      - name: cf1
        static_ips: (( static_ips(0) ))
        default: (( merge || nil ))

  - name: logs_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))

  - name: nats_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(2) ))

  - name: nfs_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(3) ))

  - name: postgres_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(4) ))

  - name: router_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(5) ))

  - name: loggregator_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(6) ))

  - name: loggregator_trafficcontroller_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(7) ))

  - name: etcd_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(8, 9, 10) ))

  - name: logs_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: nats_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: router_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: etcd_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: loggregator_z2
    instances: 0
    networks:
     - name: cf2
       static_ips: []

  - name: loggregator_trafficcontroller_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: uaa_z2
    instances: 0

  - name: api_z2
    instances: 0

  - name: api_worker_z2
    instances: 0

  - name: hm9000_z2
    instances: 0

  - name: runner_z2
    instances: 0

  - name: login_z2
    instances: 0
