empty_hash: {}

networks: (( merge ))

meta:
  environment: ~

  release:
    name: cf

  consul_servers: (( merge || jobs.consul_z1.networks.cf1.static_ips jobs.consul_z2.networks.cf2.static_ips ))

  nfs_client_ranges:
    - (( .networks.cf1.subnets.[0].range || nil ))
    - (( .networks.cf2.subnets.[0].range || nil ))

  nfs_server:
    address: (( merge || jobs.nfs_z1.networks.cf1.static_ips.[0] || nil ))
    allow_from_entries: (( merge || meta.nfs_client_ranges ))
    share: ~

  api_routes:
  - name: api
    tags:
      component: CloudController
    port: (( .properties.cc.external_port ))
    uris:
    - (( "api." .properties.domain ))

  api_templates:
  - name: cloud_controller_ng
    release: (( meta.release.name ))
  - name: routing-api
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: statsd-injector
    release: (( meta.release.name ))
  - name: consul_agent
    release: (( meta.consul_templates.consul_agent.release ))
  - name: nfs_mounter
    release: (( meta.release.name ))
  - name: route_registrar
    release: (( meta.release.name ))

  api_worker_templates:
  - name: cloud_controller_worker
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: consul_agent
    release: (( meta.consul_templates.consul_agent.release ))
  - name: nfs_mounter
    release: (( meta.release.name ))

  clock_templates:
  - name: cloud_controller_clock
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  consul_templates:
  - name: consul_agent
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  dea_templates:
  - name: dea_next
    release: (( meta.release.name ))
  - name: dea_logging_agent
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  etcd_templates:
  - name: etcd
    release: (( meta.release.name ))
  - name: etcd_metrics_server
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  ha_proxy_templates:
  - name: haproxy
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: consul_agent
    release: (( meta.consul_templates.consul_agent.release ))

  hm9000_routes:
  - name: hm9000
    port: 5155
    tags:
      component: HM9K
    uris:
    - (( "hm9000." .properties.domain ))

  hm9000_templates:
  - name: hm9000
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: route_registrar
    release: (( meta.release.name ))

  loggregator_templates:
  - name: doppler
    release: (( meta.release.name ))
  - name: syslog_drain_binder
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  loggregator_trafficcontroller_routes:
  - name: doppler
    port: (( .properties.loggregator.outgoing_dropsonde_port ))
    uris:
    - (( "doppler." .properties.domain ))
  - name: loggregator
    port: (( .properties.traffic_controller.outgoing_port ))
    uris:
    - (( "loggregator." .properties.domain ))

  loggregator_trafficcontroller_templates:
  - name: loggregator_trafficcontroller
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: route_registrar
    release: (( meta.release.name ))

  nats_templates:
  - name: nats
    release: (( meta.release.name ))
  - name: nats_stream_forwarder
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  nfs_templates:
  - name: debian_nfs_server
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  postgres_templates:
  - name: postgres
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  router_templates:
  - name: gorouter
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: consul_agent
    release: (( meta.consul_templates.consul_agent.release ))

  stats_templates:
  - name: collector
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))

  uaa_routes:
  - name: uaa
    port: (( .properties.uaa.port ))
    tags:
      component: uaa
    uris:
    - (( "uaa." .properties.domain ))
    - (( "*.uaa." .properties.domain ))
    - (( "login." .properties.domain ))
    - (( "*.login." .properties.domain ))

  uaa_templates:
  - name: uaa
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: consul_agent
    release: (( meta.consul_templates.consul_agent.release ))
  - name: route_registrar
    release: (( meta.release.name ))
  - name: statsd-injector
    release: (( meta.release.name ))

jobs:
  - name: consul_z1
    templates: (( merge || meta.consul_templates ))
    instances: 2
    persistent_disk: 1024
    resource_pool: small_z1
    networks:
      - name: cf1
        static_ips: (( merge || nil ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      consul:
        agent:
          mode: server
      metron_agent:
        zone: z1

  - name: consul_z2
    templates: (( merge || meta.consul_templates ))
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z2
    networks:
      - name: cf2
        static_ips: (( merge || nil ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      consul:
        agent:
          mode: server
      metron_agent:
        zone: z2

  - name: ha_proxy_z1
    templates: (( merge || meta.ha_proxy_templates ))
    instances: 0
    resource_pool: router_z1
    default_networks:
      - name: cf1
        static_ips: ~
    networks: (( merge || default_networks ))
    properties:
      ha_proxy:
      router:
        servers:
          z1: (( merge || jobs.router_z1.networks.cf1.static_ips ))
          z2: (( merge || jobs.router_z2.networks.cf2.static_ips ))
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: nats_z1
    templates: (( merge || meta.nats_templates ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( merge || nil ))
    properties:
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: nats_z2
    templates: (( merge || meta.nats_templates ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
        static_ips: (( merge || nil ))
    properties:
      metron_agent:
        zone: z2
    update: (( merge || empty_hash ))

  - name: etcd_z1
    templates: (( merge || meta.etcd_templates ))
    instances: 2
    persistent_disk: 10024
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( merge || nil ))
    properties:
      metron_agent:
        zone: z1
    update:
      max_in_flight: 1

  - name: etcd_z2
    templates: (( merge || meta.etcd_templates ))
    instances: 1
    persistent_disk: 10024
    resource_pool: medium_z2
    networks:
      - name: cf2
        static_ips: (( merge || nil ))
    properties:
      metron_agent:
        zone: z2
    update:
      max_in_flight: 1

  - name: stats_z1
    templates: (( merge || meta.stats_templates ))
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: nfs_z1
    templates: (( merge || meta.nfs_templates ))
    instances: 0
    resource_pool: medium_z1
    persistent_disk: 102400
    networks:
      - name: cf1
        static_ips: ~
    properties:
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: postgres_z1
    templates: (( merge || meta.postgres_templates ))
    instances: 0
    resource_pool: medium_z1
    persistent_disk: 4096
    networks:
    - name: cf1
      static_ips: ~
    properties:
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: uaa_z1
    templates: (( merge || meta.uaa_templates ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      consul:
        agent:
          services:
            uaa: {}
      metron_agent:
        zone: z1
      route_registrar:
        routes: (( merge || meta.uaa_routes ))
      uaa:
        proxy:
          servers: (( merge || jobs.router_z1.networks.cf1.static_ips jobs.router_z2.networks.cf2.static_ips))
    update: (( merge || empty_hash ))

  - name: uaa_z2
    templates: (( merge || meta.uaa_templates ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      consul:
        agent:
          services:
            uaa: {}
      metron_agent:
        zone: z2
      route_registrar:
        routes: (( merge || meta.uaa_routes ))
      uaa:
        proxy:
          servers: (( merge || jobs.router_z1.networks.cf1.static_ips jobs.router_z2.networks.cf2.static_ips))
    update: (( merge || empty_hash ))

  - name: api_z1
    templates: (( merge || meta.api_templates ))
    instances: 1
    resource_pool: large_z1
    persistent_disk: 0
    networks:
      - name: cf1
    properties:
      consul:
        agent:
          services:
            cloud_controller_ng: {}
            routing-api: {}
      metron_agent:
        zone: z1
      route_registrar:
        routes: (( merge || meta.api_routes ))
      nfs_server: (( meta.nfs_server ))
    update: (( merge || empty_hash ))

  - name: api_z2
    templates: (( merge || meta.api_templates ))
    instances: 1
    resource_pool: large_z2
    persistent_disk: 0
    networks:
      - name: cf2
    properties:
      consul:
        agent:
          services:
            cloud_controller_ng: {}
            routing-api: {}
      metron_agent:
        zone: z2
      route_registrar:
        routes: (( merge || meta.api_routes ))
      nfs_server: (( meta.nfs_server ))
    update: (( merge || empty_hash ))

  - name: clock_global
    templates: (( merge || meta.clock_templates ))
    instances: 1
    resource_pool: medium_z1
    persistent_disk: 0
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: api_worker_z1
    templates: (( merge || meta.api_worker_templates ))
    instances: 1
    resource_pool: small_z1
    persistent_disk: 0
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: z1
      nfs_server: (( meta.nfs_server ))
    update: (( merge || empty_hash ))

  - name: api_worker_z2
    templates: (( merge || meta.api_worker_templates ))
    instances: 1
    resource_pool: small_z2
    persistent_disk: 0
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: z2
      nfs_server: (( meta.nfs_server ))
    update: (( merge || empty_hash ))

  - name: hm9000_z1
    templates: (( merge || meta.hm9000_templates ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: z1
      route_registrar:
        routes: (( merge || meta.hm9000_routes ))
    update: (( merge || empty_hash ))

  - name: hm9000_z2
    templates: (( merge || meta.hm9000_templates ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: z2
      route_registrar:
        routes: (( merge || meta.hm9000_routes ))
    update: (( merge || empty_hash ))

  - name: runner_z1
    templates: (( merge || meta.dea_templates ))
    instances: 1
    resource_pool: runner_z1
    networks:
      - name: cf1
        static_ips: ~
    properties:
      dea_next:
        zone: (( merge || "z1" ))
      metron_agent:
        zone: z1
    update:
      max_in_flight: 1

  - name: runner_z2
    templates: (( merge || meta.dea_templates ))
    instances: 1
    resource_pool: runner_z2
    networks:
      - name: cf2
        static_ips: ~
    properties:
      dea_next:
        zone: (( merge || "z2" ))
      metron_agent:
        zone: z2
    update:
      max_in_flight: 1

  - name: loggregator_z1
    templates: (( merge || meta.loggregator_templates ))
    instances: 0
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      doppler:
        zone: z1
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: loggregator_z2
    templates: (( merge || meta.loggregator_templates ))
    instances: 0
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      doppler:
        zone: z2
      metron_agent:
        zone: z2
    update: (( merge || empty_hash ))

  - name: doppler_z1
    templates: (( merge || meta.loggregator_templates ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      doppler:
        zone: z1
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: doppler_z2
    templates: (( merge || meta.loggregator_templates ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      doppler:
        zone: z2
      metron_agent:
        zone: z2
    update: (( merge || empty_hash ))

  - name: loggregator_trafficcontroller_z1
    templates: (( merge || meta.loggregator_trafficcontroller_templates ))
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
    properties:
      traffic_controller:
        zone: z1
      metron_agent:
        zone: z1
      route_registrar:
        routes: (( merge || meta.loggregator_trafficcontroller_routes ))
    update: (( merge || empty_hash ))

  - name: loggregator_trafficcontroller_z2
    templates: (( merge || meta.loggregator_trafficcontroller_templates ))
    instances: 1
    resource_pool: small_z2
    networks:
      - name: cf2
    properties:
      traffic_controller:
        zone: z2
      metron_agent:
        zone: z2
      route_registrar:
        routes: (( merge || meta.loggregator_trafficcontroller_routes ))
    update: (( merge || empty_hash ))

  - name: router_z1
    templates: (( merge || meta.router_templates ))
    instances: 1
    resource_pool: router_z1
    default_networks:
      - name: cf1
        static_ips: ~
    networks: (( merge || default_networks ))
    properties:
      consul:
        agent:
          services:
            gorouter: {}
      metron_agent:
        zone: z1
    update: (( merge || empty_hash ))

  - name: router_z2
    templates: (( merge || meta.router_templates ))
    instances: 1
    resource_pool: router_z2
    default_networks:
      - name: cf2
        static_ips: ~
    networks: (( merge || default_networks ))
    properties:
      consul:
        agent:
          services:
            gorouter: {}
      metron_agent:
        zone: z2
    update: (( merge || empty_hash ))

  - name: acceptance_tests
    templates:
    - name: acceptance-tests
      release: (( meta.release.name ))
    instances: 1
    resource_pool: small_errand
    lifecycle: errand
    networks:
      - name: cf1

  - name: smoke_tests
    templates:
    - name: smoke-tests
      release: (( meta.release.name ))
    instances: 0
    resource_pool: small_errand
    lifecycle: errand
    networks:
      - name: cf1
    properties:
      <<: (( merge ))

properties:
  <<: (( merge ))
  consul:
    agent:
      log_level: (( merge || nil ))
      servers:
        lan: (( meta.consul_servers ))
    ca_cert:
    agent_cert:
    agent_key:
    encrypt_keys: (( merge || [] ))
    require_ssl:
    server_cert:
    server_key:

  dropsonde:
    enabled: true

  support_address: (( merge || "http://support.cloudfoundry.com" ))
  description: null
  domain: (( merge ))
  ssl:
    skip_cert_verify: (( merge || false ))
  system_domain: (( domain ))
  system_domain_organization: ~
  app_domains: (( [domain] ))

  disk_quota_enabled: true

  request_timeout_in_seconds: 900

  nats:
    user: (( merge ))
    password: (( merge ))
    address: (( merge || jobs.nats_z1.networks.cf1.static_ips.[0] ))
    port: 4222
    machines: (( merge || jobs.nats_z1.networks.cf1.static_ips jobs.nats_z2.networks.cf2.static_ips ))
    debug: false
    trace: false
    monitor_port: 0
    prof_port: 0

  etcd:
    machines: (( merge || jobs.etcd_z1.networks.cf1.static_ips jobs.etcd_z2.networks.cf2.static_ips ))
    require_ssl: false
    peer_require_ssl: false

  etcd_metrics_server:
    nats:
      machines: (( .properties.nats.machines ))
      username: (( .properties.nats.user ))
      password: (( .properties.nats.password ))

  dea_next:
    memory_overcommit_factor: null
    disk_overcommit_factor: null
    instance_bandwidth_limit: (( merge || nil ))
    staging_bandwidth_limit: (( merge || nil ))
    memory_mb: (( merge || nil ))
    disk_mb: (( merge || nil ))
    staging_disk_inode_limit: 200000
    instance_disk_inode_limit: 200000
    deny_networks: (( merge || [] ))
    allow_networks: (( merge || [] ))
    kernel_network_tuning_enabled: true
    directory_server_protocol: https
    evacuation_bail_out_time_in_seconds: 600
    logging_level: debug
    staging_disk_limit_mb: 6144
    staging_memory_limit_mb: 1024
    default_health_check_timeout: 60
    advertise_interval_in_seconds: 5
    heartbeat_interval_in_seconds: 10
    rlimit_core: (( merge || 0 ))
    allow_host_access: ~
    mtu: (( merge || nil ))

  loggregator:
    <<: (( merge ))
    etcd:
      machines: (( .properties.etcd.machines ))

  loggregator_endpoint:
    shared_secret: (( merge ))

  doppler_endpoint:
    shared_secret: (( .properties.loggregator_endpoint.shared_secret ))

  metron_endpoint:
    shared_secret: (( .properties.loggregator_endpoint.shared_secret ))

  logger_endpoint: ~

  cc: (( merge ))
  ccdb: (( merge ))

  ha_proxy: (( merge || nil ))

  hm9000: (( merge ))

  uaa: (( merge ))
  uaadb: (( merge ))

  databases: ~

  router:
    enable_ssl: (( merge || nil ))
    ssl_cert: (( merge || nil ))
    ssl_key: (( merge || nil ))
    cipher_suites: (( merge || nil ))
    requested_route_registration_interval_in_seconds: (( merge || nil ))
    ssl_skip_validation: (( merge || nil ))
    port: (( merge || nil ))
    status:
      user: (( merge ))
      password: (( merge ))
      port: (( merge || nil ))
    secure_cookies: (( merge || nil ))
    route_services_secret: (( merge || nil ))
    route_services_secret_decrypt_only: (( merge || nil ))
    route_services_timeout: (( merge || nil ))
    logrotate: (( merge || nil ))
    extra_headers_to_log: (( merge || nil ))
    debug_addr: (( merge || nil ))

  syslog_daemon_config: ~

  nfs_server: (( meta.nfs_server ))

  collector: (( merge || nil ))

  acceptance_tests: (( merge || nil ))

  smoke_tests: (( merge || nil ))
