meta:
  environment: ~

lamb_meta:
  release:
    name: cf

  loggregator_templates:
  - name: doppler
    release: (( lamb_meta.release.name ))
  - name: syslog_drain_binder
    release: (( lamb_meta.release.name ))
  - name: metron_agent
    release: (( lamb_meta.release.name ))

  loggregator_trafficcontroller_templates:
  - name: loggregator_trafficcontroller
    release: (( lamb_meta.release.name ))
  - name: metron_agent
    release: (( lamb_meta.release.name ))
  - name: route_registrar
    release: (( lamb_meta.release.name ))

jobs:
- name: loggregator_z1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1

- name: loggregator_z2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2

- name: doppler_z1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1

- name: doppler_z2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2

- name: loggregator_trafficcontroller_z1
  properties:
    traffic_controller:
      zone: z1
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: doppler
        port: (( .properties.loggregator.outgoing_dropsonde_port ))
        uris:
        - (( "doppler." .properties.domain ))
      - name: loggregator
        port: (( .properties.traffic_controller.outgoing_port ))
        uris:
        - (( "loggregator." .properties.domain ))

- name: loggregator_trafficcontroller_z2
  properties:
    traffic_controller:
      zone: z2
    metron_agent:
      zone: z2
    route_registrar:
      routes:
      - name: doppler
        port: (( .properties.loggregator.outgoing_dropsonde_port ))
        uris:
        - (( "doppler." .properties.domain ))
      - name: loggregator
        port: (( .properties.traffic_controller.outgoing_port ))
        uris:
        - (( "loggregator." .properties.domain ))

properties:
  <<: (( merge ))

  loggregator:
    maxRetainedLogMessages: 100
    debug: (( merge || false ))
    blacklisted_syslog_ranges: ~
    outgoing_dropsonde_port: 8081
    tls:
      ca: ~

  doppler:
    maxRetainedLogMessages: 100
    debug: (( merge || false ))
    blacklisted_syslog_ranges: ~
    unmarshaller_count: (( merge || 5 ))
    port: (( merge || 4443 ))
    enable_tls_transport: ~
    tls_server:
      cert: ~
      port: ~
      key: ~


  metron_agent:
    deployment: (( meta.environment ))
    preferred_protocol: ~
    tls_client:
      cert: ~
      key: ~

  traffic_controller:
    outgoing_port: 8080
