meta:
  syslog:
    z1: ~
    z2: ~

update:
  canaries: 0

jobs:
  - name: runner_z1
    instances: 1
    template: dea_next

  - name: runner_z2
    instances: 0
    template: dea_next

  - name: loggregator_z1
    instances: 1

  - name: loggregator_z2
    instances: 1

  - name: loggregator_trafficcontroller_z1
    instances: 1

  - name: loggregator_trafficcontroller_z2
    instances: 1

  - name: logs_z1
    instances: 0

  - name: logs_z2
    instances: 0

  - name: router_z2
    instances: 0

properties:
  ssl:
    skip_cert_verify: true
