#!/bin/bash

HM_SHADOW_PACKAGE_DIR=/var/vcap/packages/health_manager_shadow
HM_SHADOW_JOB_DIR=/var/vcap/jobs/health_manager_shadow
HM_SHADOW_CONF_DIR=$HM_SHADOW_JOB_DIR/config
RUN_DIR=/var/vcap/sys/run/health_manager_shadow
LOG_DIR=/var/vcap/sys/log/health_manager_shadow
PIDFILE=$RUN_DIR/health_manager_shadow.pid

export PATH=/var/vcap/packages/ruby/bin:$PATH

source /var/vcap/packages/common/utils.sh

case $1 in
  start)
    pid_guard $PIDFILE "Health Manager Shadow"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    chown vcap:vcap $RUN_DIR
    chown vcap:vcap $LOG_DIR

    echo $$ > $PIDFILE
    chown vcap:vcap $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $HM_SHADOW_CONF_DIR
    <% end %>

    exec chpst -u vcap:vcap $HM_SHADOW_PACKAGE_DIR/bin/health_manager \
         -c $HM_SHADOW_JOB_DIR/config/health_manager_shadow.yml \
         >>$LOG_DIR/health_manager_shadow.stdout.log \
         2>>$LOG_DIR/health_manager_shadow.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: health_manager_shadow_ctl {start|stop}"

    ;;

esac
