#!/bin/bash

set -e

pushd $(dirname $0)/.. > /dev/null
  scripts/generate-bosh-lite-dev-manifest
  bosh --parallel 10 sync blobs
  bosh create release --name cf --force
  bosh -t lite -n upload release
  bosh -t lite -n deploy
popd > /dev/null
