#!/bin/sh

set -e -x

scripts_folder=$(dirname $0)

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="dea-certs"
mkdir -p ${depot_path}

# CA to distribute to DEA clients and servers
${scripts_folder}/generate_ca_cert --common-name "deaCA" --depot-path ${depot_path} --output-file dea_ca

# Server certificate to share across the bbs cluster
server_cn=dea.service.cf.internal
server_domain='*.dea.service.cf.internal'
${scripts_folder}/generate_end_entity_certs --common-name ${server_cn} --ca-name dea_ca --domain ${server_domain} --depot-path ${depot_path} --output-file dea_server

# Client certificate to distribute to jobs that access DEAs
${scripts_folder}/generate_end_entity_certs --common-name 'dea client' --ca-name dea_ca --depot-path ${depot_path} --output-file dea_client
