#!/bin/bash

set -e -x

scripts_folder=$(dirname $0)

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="uaa-certs"
mkdir -p ${depot_path}

# CA to generate client certs
${scripts_folder}/generate_ca_cert --common-name "cert-authority" --depot-path ${depot_path} --output-file server-ca

# Certificate to use as the client
server_cn="uaa.service.cf.internal"
${scripts_folder}/generate_end_entity_certs --common-name ${server_cn} --ca-name server-ca --depot-path ${depot_path} --output-file server
