#!/bin/bash

set -ef -o pipefail

if [ -n "${CF_DEPLOYMENT_TRACE}" ]; then
  set -x
fi

set -u

# Check for spiff installation
which spiff > /dev/null 2>&1 || {
  echo "Aborted. Please install spiff by following https://github.com/cloudfoundry-incubator/spiff#installation" 1>&2
  exit 1
}

root_dir=$(cd "$(dirname "$0")/.." && pwd)

templates="${root_dir}/templates"

infrastructure="${1:?}"

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "openstack" ] && \
    [ "$infrastructure" != "bosh-lite" ] && \
    [ "$infrastructure" != "vsphere" ] && \
    [ "$infrastructure" != "gce" ] ; then
  echo "usage: ./scripts/generate_deployment_manifest <aws|openstack|bosh-lite|vsphere|gce> [stubs...]" 1>&2
  exit 1
fi

spiff merge \
  "${templates}/generic-manifest-mask.yml" \
  "${templates}/cf.yml" \
  "${templates}/cf-infrastructure-${infrastructure}.yml" \
  "$@"
