#!/bin/sh

set -e -x

source $(dirname $0)/certificate_generation_functions.sh

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="hm9000-certs"
mkdir -p ${depot_path}

# CA to distribute to DEA clients and servers
generate_ca hm9000CA ${depot_path} hm9000_ca

# Server certificate to share across the bbs cluster
server_cn=listener-hm9000.service.cf.internal
server_domain='*.listener-hm9000.service.cf.internal'
generate_end_entity_certs ${server_cn} "${server_domain},${server_cn}" hm9000_ca ${depot_path} hm9000_server

# Client certificate to distribute to jobs that access DEAs
generate_end_entity_certs hm9000_client '' hm9000_ca ${depot_path} hm9000_client
