#!/bin/sh

set -e

if [ "$1" = "" ]; then
    echo "usage: $0 <bbs-ca.crt> <bbs-ca.key>"
    echo "       $0 no-bbs-ca"
    exit 1
fi

set -x

readlink() {
  (
    cd $(dirname $1)
    echo $PWD/$(basename $1)
  )
}

# Place keys and certificates here
depot_path=$(readlink ./loggregator-certs)
mkdir -p ${depot_path}

if [ "$1" = "no-bbs-ca" ]; then
    bbs_ca_name="loggregator-ca"
else
    bbs_ca_cert_path=$(readlink ${1})
    bbs_ca_key_path=$(readlink ${2})
    bbs_ca_name=$(basename ${bbs_ca_cert_path} ".crt")
    ln -s ${bbs_ca_cert_path} ${depot_path}/
    ln -s ${bbs_ca_key_path} ${depot_path}/
fi

# Install certstrap
go get -v github.com/square/certstrap

# CA to distribute to loggregator certs
certstrap --depot-path ${depot_path} init --passphrase '' --common-name loggregatorCA
mv -f ${depot_path}/loggregatorCA.crt ${depot_path}/loggregator-ca.crt
mv -f ${depot_path}/loggregatorCA.key ${depot_path}/loggregator-ca.key
mv -f ${depot_path}/loggregatorCA.crl ${depot_path}/loggregator-ca.crl

# Doppler certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name doppler
certstrap --depot-path ${depot_path} sign doppler --CA loggregator-ca

# Traffic Controller certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name trafficcontroller
certstrap --depot-path ${depot_path} sign trafficcontroller --CA loggregator-ca

# Metron certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name metron
certstrap --depot-path ${depot_path} sign metron --CA loggregator-ca

# Reverse Log Proxy certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name reverselogproxy
certstrap --depot-path ${depot_path} sign reverselogproxy --CA loggregator-ca

# Syslog drain binder certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name syslogdrainbinder
certstrap --depot-path ${depot_path} sign syslogdrainbinder --CA ${bbs_ca_name}
