#!/usr/bin/env bash

set -e

SCRIPTS_FOLDER="$(dirname "$0")"

ROOT_DEPOT_PATH="$1"
DEPOT_PATH="statsd-injector-certs"

if [[ "$1" == "--recreate-ca" || -z "$1" || ! -d "$1" ]]; then
  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
  exit 1
fi

test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"

LOGGREGATOR_CA_CERT_PATH="$(find "$ROOT_DEPOT_PATH" -name 'loggregator-ca.crt')"
LOGGREGATOR_CA_KEY_PATH="$(find "$ROOT_DEPOT_PATH" -name 'loggregator-ca.key')"
if [[ -z "$LOGGREGATOR_CA_CERT_PATH" || -z "$LOGGREGATOR_CA_KEY_PATH" ]]; then
  echo -e "\e[1m\e[33m[ERROR] Please execute '$SCRIPTS_FOLDER/generate-loggregator-cert' before running this script.\e[0m"
  exit 1
fi

LOGGREGATOR_CA_CERT_PATH="$(custom_realpath "$LOGGREGATOR_CA_CERT_PATH")"
LOGGREGATOR_CA_KEY_PATH="$(custom_realpath "$LOGGREGATOR_CA_KEY_PATH")"
ln -s "${LOGGREGATOR_CA_CERT_PATH}" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
ln -s "${LOGGREGATOR_CA_KEY_PATH}" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"

# Statsd injector certificate
server_cn="statsdinjector.service.cf.internal"
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "${server_cn}" --ca-name loggregator-ca --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file statsdinjector

find "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" -type l -delete
