#!/bin/bash

set -eu

export BOSH_USE_BUNDLER=true

set +e
hash bundler > /dev/null 2>&1
bundler_exists=$?
set -e

if [[ "${bundler_exists}" -ne 0 ]]; then
  echo 'Bundler is not installed; install it with `gem install bundler`'
  exit 1
fi

SCRIPT_DIR=$(dirname $0)
CF_RELEASE_DIR=${CF_RELEASE_DIR:-$SCRIPT_DIR/..}

if [[ ! -d "${CF_RELEASE_DIR}" ]]; then
  echo "Cannot find cf-release at '${CF_RELEASE_DIR}'; override with \$CF_RELEASE_DIR variable"
  exit 1
fi

BOSH_STATUS=$(bosh status)
DIRECTOR_UUID=$(bosh status --uuid)
EXPECTED_DIRECTOR_NAME="Bosh Lite Director"

if [[ "$(echo "$BOSH_STATUS" | grep Name)" != *"$EXPECTED_DIRECTOR_NAME"* ]]; then
  echo "Can only target $EXPECTED_DIRECTOR_NAME. Please use 'bosh target' before running this script."
  exit 1
fi

mkdir -p "${CF_RELEASE_DIR}/bosh-lite/deployments"

mkdir uaaCerts
openssl req -newkey rsa:2048 -nodes -x509 -keyout uaaCerts/sp.key.pem -out uaaCerts/sp.cert.pem -days 1460 -subj '/'
jq -n --arg spKey "`cat uaaCerts/sp.key.pem`" --arg spCert "`cat uaaCerts/sp.cert.pem`" '{"properties":{"login":{"saml":{"serviceProviderKey":$spKey,"serviceProviderKeyPassword":"","serviceProviderCertificate":$spCert}}}}' > uaa-properties.json
rm -rf uaaCerts

"${CF_RELEASE_DIR}/scripts/generate_deployment_manifest" \
  bosh-lite \
  uaa-properties.json \
  <(echo "director_uuid: ${DIRECTOR_UUID}") \
  "$@" \
  > "${CF_RELEASE_DIR}/bosh-lite/deployments/cf.yml"

rm uaa-properties.json

bosh deployment "${CF_RELEASE_DIR}/bosh-lite/deployments/cf.yml"
