#!/bin/sh

set -e

if [ "$1" = "" ]; then
    echo "usage: $0 <bbs-ca.crt> <bbs-ca.key> <loggregator-ca.crt> <loggregator-ca.key>"
    echo "       $0 no-ca"
    exit 1
fi

# Place keys and certificates here
depot_path="scalable-syslog-certs"
mkdir -p "$depot_path"

# Install certstrap
go get -v github.com/square/certstrap

if [ "$1" = "no-ca" ]; then
    bbs_ca_name="scalable-syslog-ca"
    log_ca_name="scalable-syslog-ca"
else
    if [ "$2" = "" ] || [ "$3" = "" ] || [ "$4" = "" ]; then
        echo "usage: $0 <bbs-ca.crt> <bbs-ca.key> <loggregator-ca.crt> <loggregator-ca.key>"
        echo "       $0 no-ca"
        exit 1
    fi

    ca_cert_path=$1
    ca_key_path=$2
    bbs_ca_name=$(basename ${ca_cert_path} ".crt")
    ln -s ${ca_cert_path} ${depot_path}/
    ln -s ${ca_key_path} ${depot_path}/

    log_ca_cert_path=$3
    log_ca_key_path=$4
    log_ca_name=$(basename ${log_ca_cert_path} ".crt")
    ln -s ${log_ca_cert_path} ${depot_path}/
    ln -s ${log_ca_key_path} ${depot_path}/
fi

# CA to distribute to scalable-syslog certs
certstrap --depot-path "$depot_path" init --passphrase '' --common-name scalable-syslog-ca

# Scheduler certificate (to communicate with adapter)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-scheduler
certstrap --depot-path "$depot_path" sign ss-scheduler --CA scalable-syslog-ca

# Scheduler CAPI certificate (cert used to communicate with API to fetch
# syslog drain bindings
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-scheduler-cc
certstrap --depot-path "$depot_path" sign ss-scheduler-cc --CA "$bbs_ca_name"

# Adapter certificate (to communicate with scheduler)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-adapter
certstrap --depot-path "$depot_path" sign ss-adapter --CA scalable-syslog-ca

# Adapter RLP certificate (cert used to communicate with Reverse Logging Proxy)
certstrap --depot-path "$depot_path" request-cert --passphrase '' --common-name ss-adapter-rlp
certstrap --depot-path "$depot_path" sign ss-adapter-rlp --CA "$log_ca_name"
