#!/usr/bin/env bash

set -e

scripts_folder="$(dirname "$0")"

# Place keys and certificates here
depot_path="uaa-certs"
mkdir -p "${depot_path}"
ca_name="uaa-ca"

if [[ "$1" == "--recreate-ca" ]] || [[ -z "$1" && ! -f "$depot_path/$ca_name.crt" ]]; then
  # CA to generate client certs
  "${scripts_folder}"/generate_ca_cert --common-name "cert-authority" --depot-path "${depot_path}" --output-file "$ca_name"
elif [[ -z "$1" && -f "$depot_path/$ca_name.crt" ]]; then
  echo -e "\e[1m\e[33m[INFO] Using existing uaa CA, recreating only client/server certificates\e[0m"
fi

# Certificate to use as the client
server_cn="uaa.service.cf.internal"
"${scripts_folder}"/generate_end_entity_certs --common-name "${server_cn}" --ca-name "$ca_name" --depot-path "${depot_path}" --output-file server
