#!/usr/bin/env bash

set -e

scripts_folder="$(dirname "$0")"

if [ "$1" = "" ]; then
    echo "usage: $0 <cf-credentials-folder> [--recreate-ca]"
    exit 1
fi

readlink() {
  (
    cd "$(dirname "$1")"
    echo "$PWD/$(basename "$1")"
  )
}

# Place keys and certificates here
depot_path=$(readlink ./statsd-injector-certs)
mkdir -p "${depot_path}"

loggregator_ca_cert_path="$(find "$1/loggregator-certs" -name 'loggregator-ca.crt')"
loggregator_ca_key_path="$(find "$1/loggregator-certs" -name 'loggregator-ca.key')"
if [[ ! -f "$loggregator_ca_cert_path" || ! -f "$loggregator_ca_key_path" ]]; then
    echo -e "\e[1m\e[33m[ERROR] Please execute generate-loggregator-certs before running this script.\e[0m"
    exit 1
fi

find "$depot_path" -type l -delete
ln -s "${loggregator_ca_cert_path}" "${depot_path}/"
ln -s "${loggregator_ca_key_path}" "${depot_path}/"

# Statsd injector certificate
server_cn="statsdinjector.service.cf.internal"
"${scripts_folder}"/generate_end_entity_certs --common-name "${server_cn}" --ca-name loggregator-ca --depot-path "${depot_path}" --output-file statsdinjector

find "$depot_path" -type l -delete
