#!/bin/sh

set -e -x

source $(dirname $0)/certificate_generation_functions.sh

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="dea-certs"
mkdir -p ${depot_path}

# CA to distribute to DEA clients and servers
generate_ca deaCA ${depot_path} dea_ca

# Server certificate to share across the bbs cluster
server_cn=dea.service.cf.internal
server_domain='*.dea.service.cf.internal'
generate_end_entity_certs ${server_cn} ${server_domain} dea_ca ${depot_path} dea_server

# Client certificate to distribute to jobs that access DEAs
generate_end_entity_certs 'dea client' '' dea_ca ${depot_path} dea_client
