#!/bin/sh

set -e -x

scripts_folder=$(dirname $0)

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="hm9000-certs"
mkdir -p ${depot_path}

# CA to distribute to DEA clients and servers
${scripts_folder}/generate_ca_cert --common-name "hm9000CA" --depot-path ${depot_path} --output-file hm9000_ca

# Server certificate to share across the bbs cluster
server_cn=listener-hm9000.service.cf.internal
server_domain='*.listener-hm9000.service.cf.internal'
${scripts_folder}/generate_end_entity_certs --common-name ${server_cn} --domain "${server_domain},${server_cn}" --ca-name hm9000_ca --depot-path ${depot_path} --output-file hm9000_server

# Client certificate to distribute to jobs that access DEAs
${scripts_folder}/generate_end_entity_certs --common-name hm9000_client --ca-name hm9000_ca --depot-path ${depot_path} --output-file hm9000_client
