#!/bin/sh

set -e -x

source $(dirname $0)/certificate_generation_functions.sh

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path=$1
mkdir -p ${depot_path}

# CA to generate client certs
generate_ca "cert-authority" ${depot_path} server-ca

# Certificate to use as the client
server_cn=$2
generate_end_entity_certs ${server_cn} "" server-ca ${depot_path} server

