#!/bin/sh

set -e -x

source $(dirname $0)/certificate_generation_functions.sh

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="consul-certs"
mkdir -p ${depot_path}

generate_ca consulCA ${depot_path} server-ca

# Server certificate to share across the consul cluster
generate_end_entity_certs server.dc1.cf.internal "" server-ca ${depot_path} server

# Agent certificate to distribute to jobs that access consul
generate_end_entity_certs 'consul agent' "" server-ca ${depot_path} agent
