#!/usr/bin/env bash

set -e

SCRIPTS_FOLDER="$(dirname "$0")"

ROOT_DEPOT_PATH="$1"
DEPOT_PATH="loggregator-certs"
CA_NAME="loggregator-ca"
BBS_CA_NAME="$CA_NAME"

function create_ca {
  "${SCRIPTS_FOLDER}"/generate_ca_cert --common-name "loggregatorCA" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file "$CA_NAME"
}

if [[ "$1" == "--recreate-ca" || "$1" == "no-bbs-ca" || -z "$1" || ! -d "$1" ]]; then
  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
  exit 1
fi

test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"

if [[ "$2" == "--recreate-ca" ]]; then
  echo -e "\e[1m\e[33m[INFO] Recreating only the loggregatorCA. To recreate the diegoCA, please execute the script '$SCRIPTS_FOLDER/generate-cf-diego-certs'\e[0m"
  create_ca
elif [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
  create_ca
fi

if [[ -z "$3" || "$3" != "--no-bbs-ca" ]]; then
  bbs_ca_cert_path="$(find "$ROOT_DEPOT_PATH" -name 'cf-diego-ca.crt')"
  bbs_ca_key_path="$(find "$ROOT_DEPOT_PATH" -name 'cf-diego-ca.key')"
  if [[ -z "$bbs_ca_cert_path" || -z "$bbs_ca_key_path" ]]; then
    echo -e "\e[1m\e[33m[ERROR] Please execute '$SCRIPTS_FOLDER/generate-cf-diego-certs' before running this script.\e[0m"
    exit 1
  fi
  bbs_ca_cert_path="$(realpath "$bbs_ca_cert_path")"
  bbs_ca_key_path="$(realpath "$bbs_ca_key_path")"
  BBS_CA_NAME="cf-diego-ca"
  ln -s "$bbs_ca_cert_path" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
  ln -s "$bbs_ca_key_path" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
fi

find "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" -type f -not -name "$CA_NAME*" -not -name "cf-diego-ca*" -delete

# Doppler certificate
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name doppler-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file doppler

# Traffic Controller certificate
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name trafficcontroller-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file trafficcontroller

# Traffic Controller<->CAPI mutual TLS certificate
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name cc_trafficcontroller-cn --ca-name "$BBS_CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file cc_trafficcontroller

# Metron certificate
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name metron-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file metron

# Reverse Log Proxy certificate
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name reverselogproxy-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file reverselogproxy

# Syslog drain binder certificate
"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name syslogdrainbinder-cn --ca-name "$BBS_CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file syslogdrainbinder

find "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" -type l -name "cf-diego-ca*" -delete
