#!/bin/bash

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

source $(dirname $0)/certificate_generation_functions.sh

# Place keys and certificates here
depot_path="uaa-certs"
mkdir -p ${depot_path}

# CA to generate client certs
generate_ca "cert-authority" ${depot_path} server-ca

# Certificate to use as the client
server_cn="uaa.service.cf.internal"
generate_end_entity_certs ${server_cn} "" server-ca ${depot_path} server
