#!/bin/sh

set -e -x

source $(dirname $0)/certificate_generation_functions.sh

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="etcd-certs"
mkdir -p ${depot_path}

# CA to distribute to etcd clients and servers
generate_ca "etcdCA" etcd-certs "etcd-ca"

# Server certificate to share across the etcd cluster
generate_end_entity_certs "cf-etcd.service.cf.internal" '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' etcd-ca etcd-certs server

# Client certificate to distribute to jobs that access etcd
generate_end_entity_certs "clientName" "" etcd-ca etcd-certs client

# CA to distribute across etcd peers
generate_ca "peerCA" etcd-certs "peer-ca"

# Client certificate to distribute across etcd peers
generate_end_entity_certs cf-etcd.service.cf.internal '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' peer-ca etcd-certs peer
