#!/bin/bash

root_dir=$(cd $(dirname $0)/.. && pwd)
cd $root_dir 

git submodule --quiet foreach '                                                                                \
  git fetch origin master &> /dev/null &&                               # make sure we are up-to-date  \
  REPO=`echo $name | sed s/src\\\///g ` && \
  GITCOUNT=`git log head...FETCH_HEAD --oneline | wc -l` && \
  echo $REPO $GITCOUNT
'
