#!/bin/bash

set -eu

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

scripts_dir=$(cd $(dirname $0) && pwd)
export GOPATH=$(cd ${scripts_dir}/.. && pwd)

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    package_dir=$(cd $(dirname $0)/../packages && pwd)
    cd ${package_dir}/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub/g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package route_registrar -app  github.com/cloudfoundry-incubator/route-registrar

git diff --name-only packages/*/spec
