#!/bin/bash

set -u -o pipefail

set +e
hash bundler > /dev/null 2>&1
bundler_exists=$?
set -e

if [[ "${bundler_exists}" -ne 0 ]]; then
  echo 'Bundler is not installed; install it with `gem install bundler`'
  exit 1
fi

pushd "$(dirname "$0")" > /dev/null
  SCRIPT_DIR=$(pwd)
popd > /dev/null

cd "${SCRIPT_DIR}/.."

bundle install

export BOSH_USE_BUNDLER=true

exec 3>&1
output=$(bundle exec bosh --color --parallel 5 sync blobs | tee >(cat - >&3))

set +e
echo "${output}" | grep -q -i "no blobs to upload"
blobs_to_upload=$?
set -e

if [[ "${blobs_to_upload}" -ne 0 ]]; then
  echo 'You need to upload new blobs. Upload them with `bosh upload blobs`'
  exit 1
fi

bundle exec rspec
