#!/bin/bash

set -eu

set +e
hash bundler > /dev/null 2>&1
bundler_exists=$?
set -e

if [[ "${bundler_exists}" -ne 0 ]]; then
  echo 'Bundler is not installed; install it with `gem install bundler`'
  exit 1
fi

pushd $(dirname $0) > /dev/null
  SCRIPT_DIR=$(pwd)
popd > /dev/null

cd ${SCRIPT_DIR}/..

bundle install

export BOSH_USE_BUNDLER=true
bundle exec bosh --parallel 5 sync blobs

${SCRIPT_DIR}/unused_blobs &&
${SCRIPT_DIR}/unused_packages &&
bundle exec rspec
