#!/bin/bash -e

pushd $(dirname $0) > /dev/null
  SCRIPT_DIR=$(pwd)
popd > /dev/null

cd ${SCRIPT_DIR}/..

bundle install

export BOSH_USE_BUNDLER=true
bundle exec bosh --parallel 5 sync blobs

${SCRIPT_DIR}/unused_blobs &&
${SCRIPT_DIR}/unused_packages &&
bundle exec rspec
