#!/bin/sh
set -e

echo ""
echo "===> Uncommitted submodules changes will be clobbered <==="
echo ""
echo ""
echo "===> Unversioned changes will be clobbered <==="
echo ""

root_dir=$(cd $(dirname $0)/.. && pwd)
cd $root_dir

set -x # show the commands we are running

git rev-parse @{u} > /dev/null 2>&1 && git pull

# Update submodule pointers
git submodule sync --recursive

# Update submodule content, checkout if necessary
git submodule update --init --recursive --force

# Clean out any submodule changes
git submodule foreach --recursive 'git clean -ffd'

git clean -ffd

set +x # stop showing commands

echo "CF Release has been updated"
