#!/bin/bash

VBLOB_ADMIN_USER=<%= properties.vblob_gateway.admin_user   || "vblob_admin" %>
VBLOB_ADMIN_GROUP=<%= properties.vblob_gateway.admin_group || "admin" %>
VBLOB_ADMIN_PASSWD_HASH=<%= properties.vblob_gateway.admin_passwd_hash || "" %>

if [ -n "$VBLOB_ADMIN_PASSWD_HASH" ]; then
    # do a mod in addition to the add in order to support password changes
    USER_ARGS="-g $VBLOB_ADMIN_GROUP -p $VBLOB_ADMIN_PASSWD_HASH $VBLOB_ADMIN_USER"
    /usr/sbin/useradd -m -s /bin/bash $USER_ARGS
    /usr/sbin/usermod $USER_ARGS
fi

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/vblob_gateway
LOG_DIR=/var/vcap/sys/log/vblob_gateway
PIDFILE=$RUN_DIR/vblob_gateway.pid
CONF_DIR=/var/vcap/jobs/vblob_gateway/config

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "vBlob gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    # Enable log aggregation
    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $CONF_DIR
    <% end %>

    exec /var/vcap/packages/vblob_gateway/services/vblob/bin/vblob_gateway -c /var/vcap/jobs/vblob_gateway/config/vblob_gateway.yml >>$LOG_DIR/vblob_gateway.stdout.log 2>>$LOG_DIR/vblob_gateway.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: vblob_gateway_ctl {start|stop}" ;;

esac
exit 0
