#!/bin/bash

RUN_DIR=/var/vcap/sys/run/syslog_aggregator
LOG_DIR=/var/vcap/store/log
JOB_DIR=/var/vcap/jobs/syslog_aggregator
BIN_DIR=$JOB_DIR/bin
PIDFILE=$RUN_DIR/nats_stream_forwarder.pid

source /var/vcap/packages/common/utils.sh

case $1 in
  start)
    pid_guard $PIDFILE "NATS Stream Forwarder"

    mkdir -p $RUN_DIR
    PATH=/var/vcap/bosh/bin:$PATH

    echo $$ > $PIDFILE
    exec $BIN_DIR/nats_stream_forwarder.rb 'nats://<%= p("nats.user") %>:<%= p("nats.password") %>@<%= p("nats.address") %>:<%= p("nats.port") %>' \
      >>$LOG_DIR/nats_stream_forwarder.stdout.log \
      2>>$LOG_DIR/nats_stream_forwarder.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: nats_stream_forwarder_ctl {start|stop}"

    ;;

esac
