#!/bin/bash

set -u

LOG_DIR=/var/vcap/store/log
# Reap logs that are older than 7 days
DAYS_TO_KEEP=7
let "MIN_TO_KEEP=${DAYS_TO_KEEP}*24*60"

# get the last $DAYS_TO_KEEP date to exclude from the rmdir

DAYS_TO_EXCLUDE=$(
for i in $(seq 0 ${DAYS_TO_KEEP}); do
    date -d "now - $i days" +%Y/%m/%d
done
)
# example output: "2012/09/21|2012/09/20|.....|2012/09/15|2012/09/14"
EGREP_FORMAT_DAYS_TO_EXCLUDE=$(echo $DAYS_TO_EXCLUDE | tr ' ' '|')

find ${LOG_DIR} -mmin +${MIN_TO_KEEP} -name '*.log.gz' -exec rm -f '{}' \;

# Reap empty dirs in 3 passes, clear empty 'day' dirs, then 'month'
# and lastly 'year'
for i in '/[0-9]{4}/[0-1][0-9]/[0-9]{2}$' \
         '/[0-9]{4}/[0-1][0-9]$' \
         '/[0-9]{4}$'; do
    /usr/bin/find ${LOG_DIR} -type d -empty |
      egrep -v "${EGREP_FORMAT_DAYS_TO_EXCLUDE}" |
      egrep ${i} |
      xargs -r -n 200 rmdir
done
