#!/bin/bash
# Reap logs that are older than 7 days

LOG_DIR=/var/vcap/store/log
find ${LOG_DIR} -mmin +10080 -name '*.log.gz' -exec rm -f '{}' \;

# Reap empty dirs in 2 passes, one to clear empty 'day' dirs and a
# second to clear empty 'month' dirs
for i in '/[0-9]{4}/[0-1][0-9]/[0-9]{2}' '/[0-9]{4}/[0-1][0-9]'; do
    /usr/bin/find ${LOG_DIR} -type d -empty | egrep ${i} | xargs -r -n 200 rmdir
done
