#!/bin/bash
<%
service = "postgresql"
plan_enabled = properties.service_plans && properties.service_plans.send(service.to_sym)
plan = properties.plan || "free"
plan_conf = plan_enabled && properties.service_plans.send(service.to_sym).send(plan.to_sym).configuration
%>
STOP_TIMEOUT=<%= properties.postgresql_node.instance_stop_timeout || 3 %>
OP=$1
BASE_DIR=$2
LOG_DIR=$3
PIDFILE=$BASE_DIR/service.pid

source /var/vcap/packages/common/utils.sh
exec 1>> $LOG_DIR/$SCRIPT.log
exec 2>> $LOG_DIR/$SCRIPT.err.log

INITDB_DIR=$PACKAGE_DIR/initdb
FIRST_TIME=0

case $OP in
  start)
    BIN_DIR=$4
    PORT=$5
    echo `date` >> $LOG_DIR/postgresql_ctl.log

    if [ ! -d $BASE_DIR -o ! -f $BASE_DIR/postgresql.conf ]; then
      FIRST_TIME=1
      mkdir -p $BASE_DIR
      chown vcap:vcap $BASE_DIR

      # copy initdb
      rsync -arl $BIN_DIR/initdb/* $BASE_DIR

      if [ $? != 0 ]; then
        echo "ERROR: Unable to initialize PostgreSQL DB" >> $LOG_DIR/postgresql_ctl.log
        exit 1
      fi
      # set listening address if supplied
      sed -i "s/#listen_addresses\( *\)=\( *\)'localhost'/listen_addresses\1=\2'*'/" $BASE_DIR/postgresql.conf
    fi

    rsync -arl $BIN_DIR/initdb/pg_hba.conf $BASE_DIR/pg_hba.conf

    chown -R vcap:vcap $BASE_DIR
    chmod -R 700 $BASE_DIR

    # host server could connect the container without password
    host_ip=`cat /etc/hosts | grep " host$"| cut -d' ' -f1`
    echo "host all all $host_ip/32 trust" >> $BASE_DIR/pg_hba.conf
    echo "host all all 0.0.0.0/0 md5" >> $BASE_DIR/pg_hba.conf

    # since postgresql service is alive
    # log dir change should cover both clean deploy and upgrade push
    if [ ! -d $LOG_DIR ]; then
      mkdir -p $LOG_DIR
      chown vcap:vcap $LOG_DIR
    fi
    sed -i "/log_directory/ {s/#log_directory/log_directory/;s|pg_log|$LOG_DIR|}" $BASE_DIR/postgresql.conf

    # set adjustable configurations per plan
    <%
    adjustable_configs = {
      :max_connections => [500, nil],
      :shared_buffers => [128, 'MB'],
      :effective_cache_size => [128, 'MB'],
      :work_mem => [1, 'MB'],
      :temp_buffers => [1, 'MB'],
      :wal_buffers => [1, 'MB'],
      :maintenance_work_mem => [30, 'MB'],
      :checkpoint_segments => [16, nil],
      :checkpoint_segments_max => [300, nil],
      :max_prepared_transactions => [0, nil],
      :port => ['$PORT', nil],
    } %>

    <% adjustable_configs.each do |config, default_value| %>
    <% value = plan_conf && plan_conf.respond_to?(config) && plan_conf.send(config)? plan_conf.send(config) : default_value[0] %>
    <% units = default_value[1] %>
    <% config = config.to_s %>
    sed -i "s/^[\w|#]*<%=config%> = .*/<%=config%> = <%=value%><%=units%>/" $BASE_DIR/postgresql.conf
    <% end %>

    # stop psql from adding timestamps to its log file names
    sed -i "/log_filename/ {s/#log_filename/log_filename/;s/postgresql-%Y-%m-%d_%H%M%S.log/postgresql.log/}" $BASE_DIR/postgresql.conf

    echo "Starting PostgreSQL `cat $BASE_DIR/PG_VERSION`: " >> $LOG_DIR/postgresql_ctl.log
    LD_LIBRARY_PATH=$BIN_DIR/lib:$LD_LIBRARY_PATH $BIN_DIR/bin/pg_ctl -w start -D $BASE_DIR -l "$LOG_DIR/startup.log"

    if [ $? == 0 ]; then
      echo "PostgreSQL `cat $BASE_DIR/PG_VERSION` started successfully" >> $LOG_DIR/postgresql_ctl.log
      head -1 $BASE_DIR/postmaster.pid > $PIDFILE
      if [ $FIRST_TIME -eq 1 ]; then
        # Setup contrib packages
        for sqlf in citext.sql fuzzystrmatch.sql isn.sql ltree.sql pageinspect.sql pg_buffercache.sql pgcrypto.sql pg_freespacemap.sql sslinfo.sql tablefunc.sql uuid-ossp.sql
        do
          echo "Installing contrib package ${sqlf}" >> $LOG_DIR/postgresql_ctl.log
          ${BIN_DIR}/bin/psql -U vcap -f ${BIN_DIR}/share/${sqlf} -d postgres >> $LOG_DIR/postgresql_ctl.log
        done
      fi
      echo `date` >> $LOG_DIR/postgresql_ctl.log
    else
      echo "The PostgreSQL server start seems to have some problems, please see logs for details." >> $LOG_DIR/postgresql_ctl.log
      exit 1
    fi
    ;;

  stop)
    BIN_DIR=$4
    LD_LIBRARY_PATH=$BIN_DIR/lib:$LD_LIBRARY_PATH $BIN_DIR/bin/pg_ctl stop -m fast -w -D $BASE_DIR
    wait_pidfile $PIDFILE 0 $STOP_TIMEOUT
    ;;

  status)
    [ -f $PIDFILE ] && [ -e /proc/`head -1 $PIDFILE` ]
    ;;

  *)
    echo "Usage: $0 {start|stop|status}"
    ;;

esac
