#!/bin/bash

export PATH=$PATH:/var/vcap/packages/ruby/bin

RUN_DIR=/var/vcap/sys/run/echo_gateway
LOG_DIR=/var/vcap/sys/log/echo_gateway
PIDFILE=$RUN_DIR/echo_gateway.pid
JOB_DIR=/var/vcap/jobs/echo_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Echo gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/echo_gateway/services/echo/bin/echo_gateway \
         -c $JOB_DIR/config/echo_gateway.yml \
         >>$LOG_DIR/echo_gateway.stdout.log \
         2>>$LOG_DIR/echo_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: echo_gateway_ctl {start|stop}"

    ;;

esac
