#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
require 'fileutils'
require 'logger'
require 'net/http'
require 'httpclient'

# Provides functionality similar to `bundle package`, but without needing
# to install any gems.

unless ARGV.length == 3
  puts "Usage: fetch_gems [/path/to/Gemfile] [/path/to/Gemfile.lock] [/path/to/store]"
  exit 1
end

gemfile_path, lockfile_path, gem_store_dir = ARGV.map {|path| File.expand_path(path) }

ENV['BUNDLE_GEMFILE'] = gemfile_path

lockfile_contents = File.read(lockfile_path)
parser = Bundler::LockfileParser.new(lockfile_contents)

logger = Logger.new(STDOUT)

if parser.specs.empty?
  logger.info("No gems found")
  exit 0
end

FileUtils.mkdir_p(gem_store_dir)

to_fetch = []
parser.specs.each do |spec|
  gem_basename = "#{spec.name}-#{spec.version}.gem"
  dst_path = File.join(gem_store_dir, gem_basename)
  if spec.source.kind_of?(Bundler::Source::Path) && (spec.source.path.to_s == '.')
    logger.info("Skipping '#{gem_basename}', Gemfile.lock appears to belong to it")
  elsif File.exist?(dst_path)
    logger.info("Skipping '#{gem_basename}', found in '#{gem_store_dir}'")
  else
    logger.info("Need to download '#{gem_basename}'")
    to_fetch << gem_basename
  end
end

if to_fetch.empty?
  logger.info("Done")
  exit 0
end

def download(uri, file)
  client = HTTPClient.new
  response = client.get(uri) do |block|
    file.write(block)
  end
end

raise ArgumentError, "$RELEASE_DIR expected but not found" unless ENV["RELEASE_DIR"]

to_fetch.map do |gem_basename|
  logger.info("Fetching #{gem_basename} from rubygems")
  begin
    target = "#{gem_store_dir}/#{gem_basename}"
    cache_store = File.join(ENV["RELEASE_DIR"], ".cache", "fetch_gems")
    Dir.mkdir(cache_store) unless File.directory?(cache_store)
    cached = File.join(cache_store, gem_basename)
    if File.exist?(cached)
      FileUtils.copy(cached, target)
      logger.info("Found cached #{gem_basename}, happy")
      next
    end
    File.open(cached, "wb") do |file|
      uri = URI.parse("http://production.s3.rubygems.org/gems/#{gem_basename}")
      download(uri, file)
    end
    FileUtils.copy(cached, target)
  rescue => e
    logger.error("Failed to fetch #{gem_basename}, #{e.message}")
    FileUtils.rm_f("#{gem_store_dir}/#{gem_basename}") if File.exists?("#{gem_store_dir}/#{gem_basename}")
    exit -1
  end
end

logger.info("Done")
