#!/bin/bash -e

HBASE_BIN="/var/vcap/packages/hbase/bin"
LOG_DIR="/var/vcap/sys/log/hbase_master"
RUN_DIR="/var/vcap/sys/run/hbase_master"

PIDFILE="${RUN_DIR}/hbase-vcap-master.pid"

export HADOOP_HOME="/var/vcap/packages/hadoop"
export HBASE_CONF_DIR="/var/vcap/jobs/hbase_master/config/hbase"
export HBASE_HEAPSIZE=<%= properties.hbase_master.hbase_master.heap_size %>
export HBASE_IDENT_STRING="vcap"
export HBASE_LOG_DIR=$LOG_DIR
export HBASE_PID_DIR=$RUN_DIR
export JAVA_HOME="/var/vcap/packages/dea_jvm"

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    # hbase-daemon.sh has its own pid guard,
    # we use ours for consistency anyway
    pid_guard $PIDFILE "hbase_master"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    . ${HBASE_BIN}/hbase-config.sh
    errCode=$?
    if [ $errCode -ne 0 ]
    then
      exit $errCode
    fi

    # HBase ctl scripts manage their pidfiles,
    # so we don't attempt to write ours
    exec chpst -u vcap:vcap ${HBASE_BIN}/hbase-daemon.sh --config "${HBASE_CONF_DIR}" start master \
         >>$LOG_DIR/hbase_master_start.stdout.log \
         2>>$LOG_DIR/hbase_master_start.stderr.log

    ;;

  stop)

    exec chpst -u vcap:vcap ${HBASE_BIN}/hbase-daemon.sh --config "${HBASE_CONF_DIR}" stop master \
         >>$LOG_DIR/hbase_master_stop.stdout.log \
         2>>$LOG_DIR/hbase_master_stop.stderr.log

    ;;

  *)
    echo "Usage: hbase_master_ctl {start|stop}"

    ;;

esac
