#!/bin/bash

RUN_DIR=/var/vcap/sys/run/nginx
LOG_DIR=/var/vcap/sys/log/nginx
UPLOADS_DIR=/var/vcap/data/serialization_data_server/tmp/uploads
PIDFILE=$RUN_DIR/nginx.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Nginx"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    if [ ! -d "$UPLOADS_DIR" ]; then
      mkdir -p $UPLOADS_DIR
      chown -R vcap:vcap $UPLOADS_DIR
    fi

    exec /var/vcap/packages/nginx/sbin/nginx \
         -c /var/vcap/jobs/serialization_data_server/config/nginx.conf \
         >>$LOG_DIR/nginx.stdout.log \
         2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"

    ;;

esac
