#!/bin/bash

export ERLANG_HOME=/var/vcap/packages/erlang
export PATH=/var/vcap/packages/erlang/bin:/var/vcap/packages/ruby/bin:$PATH
export HOME=/home/vcap
RUN_DIR=/var/vcap/sys/run/rabbit_node
LOG_DIR=/var/vcap/sys/log/rabbit_node
SERV_LOG_DIR=/var/vcap/sys/service-log/rabbit
PIDFILE=$RUN_DIR/rabbit_node.pid
JOB_DIR=/var/vcap/jobs/rabbit_node
MIG_DIR=<%= properties.service_migration && properties.service_migration.mount_point || "/var/vcap/services_migration" %>

source /var/vcap/packages/common/utils.sh

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Rabbit node"
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SERV_LOG_DIR

    # Enable log aggregation
    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    # create service migration directory
    if [ ! -d $MIG_DIR ]; then
      mkdir -p $MIG_DIR
    fi

    (crontab -l | sed /rabbit_logrotate/d; cat /var/vcap/jobs/rabbit_node/config/rabbit_logrotate.cron) | sed /^$/d | crontab

    echo $$ > $PIDFILE
    exec /var/vcap/packages/rabbit_node/services/rabbit/bin/rabbit_node \
        -c $JOB_DIR/config/rabbit_node.yml \
        >>$LOG_DIR/rabbit_node.stdout.log \
        2>>$LOG_DIR/rabbit_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE 400 0

    crontab -l | sed /rabbit_logrotate/d | crontab

    ;;

  *)
    echo "Usage: rabbit_node_ctl {start|stop}"

    ;;

esac
