#!/bin/bash

RUN_DIR=/var/vcap/sys/run/warden
LOG_DIR=/var/vcap/sys/log/warden
JOB_DIR=/var/vcap/jobs/rabbit_node
PIDFILE=$RUN_DIR/warden.pid
WARDEN_SOURCE_DIR=/var/vcap/packages/rabbit_node/warden
RABBITMQ_DIR=`readlink /var/vcap/packages/rabbitmq`
ERLANG_DIR=`readlink /var/vcap/packages/erlang`
RABBITMQ_WARDEN_DIR=/var/vcap/packages/rabbit_node/warden/root/linux/base/rootfs/$RABBITMQ_DIR
ERLANG_WARDEN_DIR=/var/vcap/packages/rabbit_node/warden/root/linux/base/rootfs/$ERLANG_DIR
WARDEN_PACKAGES_DIR=/var/vcap/packages/rabbit_node/warden/root/linux/base/rootfs/var/vcap/packages

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Warden"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    echo $$ > $PIDFILE

    dpkg --install --skip-same-version /var/vcap/packages/rabbit_node/libnl1_1.1-5build1_amd64.deb
    dpkg --install --skip-same-version /var/vcap/packages/rabbit_node/quota_3.17-6_amd64.deb

    rootfs_path=/var/vcap/data/warden/rootfs
    mkdir -p $rootfs_path
    rootfs_tgz=/var/vcap/stemcell_base.tar.gz

    # Extract rootfs if needed
    if [ ! -d $rootfs_path ]
    then
      # Extract to temporary path, then rename to target path.
      # This makes sure that it is not possible that we end up with directory
      # that contains a partially extracted archive.
      tmp_path=$(mktemp --tmpdir=$(dirname $rootfs_path) -d)
      chmod 755 $tmp_path
      tar -C $tmp_path -zxf $rootfs_tgz
      mv $tmp_path $rootfs_path
    fi

    # Copy rabbitmq and erlang binaries and configuration files to warden base file system
    mkdir -p $RABBITMQ_WARDEN_DIR
    mkdir -p $ERLANG_WARDEN_DIR
    cp -af $RABBITMQ_DIR/* $RABBITMQ_WARDEN_DIR
    cp -af $ERLANG_DIR/* $ERLANG_WARDEN_DIR
    mkdir -p $WARDEN_PACKAGES_DIR
    cd $WARDEN_PACKAGES_DIR
    ln -s ../../../$ERLANG_DIR erlang
    ln -s ../../../$RABBITMQ_DIR rabbitmq
    cp -f $JOB_DIR/bin/rabbitmq_startup.sh $rootfs_path/usr/bin
    chmod 755 $rootfs_path/usr/bin/rabbitmq_startup.sh
    cp -f $JOB_DIR/config/services.conf $rootfs_path/etc/init/services.conf
    chmod 0644 $rootfs_path/etc/init/services.conf

    cd /var/vcap/packages/rabbit_node/warden
    export PATH=/var/vcap/packages/ruby/bin:$PATH
    exec /var/vcap/packages/ruby/bin/bundle exec \
         rake warden:start[$JOB_DIR/config/warden.yml] \
         >>$LOG_DIR/warden.stdout.log \
         2>>$LOG_DIR/warden.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"

    ;;

esac
