---
name: rails3

runtimes:
  - ruby18:
      description: Ruby 1.8
      version: 1.8.7
      executable: /var/vcap/packages/dea_ruby18/bin/ruby
      default: true
      environment:
        bundle_gemfile:
        path: /var/vcap/packages/dea_transition/rubygems/1.8/bin:/var/vcap/packages/dea_ruby18/bin:$PATH
        gem_path: /var/vcap/packages/dea_transition/rubygems/1.8:$GEM_PATH

  - ruby19:
      description: Ruby 1.9
      version: 1.9.2p180
      executable: /var/vcap/packages/dea_ruby19/bin/ruby
      environment:
        bundle_gemfile:
        path: /var/vcap/packages/dea_transition/rubygems/1.9.1/bin:/var/vcap/packages/dea_ruby19/bin:$PATH
        gem_path: /var/vcap/packages/dea_transition/rubygems/1.9.1:$GEM_PATH

app_servers:
  - thin:
      description: Thin
      executable: false
      default: true

detection:
  - config/application.rb: true
  - config/environment.rb: true

staged_services:
  - name: mysql
    version: *
  - name: postgresql
    version: *
