#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/mysql_node
LOG_DIR=/var/vcap/sys/log/mysql_node
PIDFILE=$RUN_DIR/mysql_node.pid
JOB_DIR=/var/vcap/jobs/mysql_node
MY_LD_FILE=/etc/ld.so.conf.d/mysql.conf

<%
migration = properties.service_migration
%>

MIG_DIR=<%= (migration && migration.mount_point) ? migration.mount_point : "/var/vcap/services_migration" %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "MySQL node"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    echo "/var/vcap/packages/mysqlclient/lib/mysql" > $MY_LD_FILE
    echo "/var/vcap/packages/mysql/lib/mysql" >> $MY_LD_FILE

    /sbin/ldconfig

    if [ ! -d $MIG_DIR ]; then
      mkdir -p $MIG_DIR
    fi

    chmod +x $JOB_DIR/config/mysql_backup
    $JOB_DIR/config/mysql_backup start

    exec /var/vcap/packages/mysql_node/bin/services/mysql_node \
         -c $JOB_DIR/config/mysql_node.yml \
         >>$LOG_DIR/mysql_node.stdout.log \
         2>>$LOG_DIR/mysql_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    chmod +x $JOB_DIR/config/mysql_backup
    $JOB_DIR/config/mysql_backup stop

    rm $MY_LD_FILE
    /sbin/ldconfig

    ;;

  *)
    echo "Usage: mysql_node_ctl {start|stop}"

    ;;

esac
