#!/bin/bash
export PATH=/var/vcap/packages/ruby/bin:$PATH

INDEX=$2
RUN_DIR=/var/vcap/sys/run/mysql_node
LOG_DIR=/var/vcap/sys/log/mysql_node
PIDFILE=$RUN_DIR/mysql_worker_$INDEX.pid
JOB_DIR=/var/vcap/jobs/mysql_node

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "MySQL worker"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    export CLOUD_FOUNDRY_CONFIG_PATH=$JOB_DIR/config/
    export PIDFILE=$PIDFILE

    exec /var/vcap/packages/mysql_node/services/mysql/bin/mysql_worker \
         >>$LOG_DIR/mysql_worker_$INDEX.stdout.log \
         2>>$LOG_DIR/mysql_worker_$INDEX.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: mysql_worker_ctl {start|stop}"

    ;;

esac
