#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/postgresql_gateway
LOG_DIR=/var/vcap/sys/log/postgresql_gateway
JOB_DIR=/var/vcap/jobs/postgresql_gateway

PIDFILE=$RUN_DIR/postgresql_gateway.pid

<%
lifecycle = properties.service_lifecycle
%>

<% if lifecycle and lifecycle.nfs_server %>
SNAPSHOT_DIR=<%= lifecycle.mount_point || "/var/vcap/services_snapshot" %>
MT_OPTS="-t nfs"
MT_EXPORT=<%= lifecycle.nfs_server.address %>:<%= lifecycle.nfs_server.export_dir %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "PostgreSQL gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    PG_ADMIN_USER=<%= properties.postgresql_gateway.admin_user || "pg_admin" %>
    PG_ADMIN_GROUP=<%= properties.postgresql_gateway.admin_group || "admin" %>
    PG_ADMIN_PASSWD_HASH=<%= properties.postgresql_gateway.admin_passwd_hash || "" %>

    if [ -n "$PG_ADMIN_PASSWD_HASH" ]; then
      # do a mod in addition to the add in order to support password changes
      USER_ARGS="-g $PG_ADMIN_GROUP -p $PG_ADMIN_PASSWD_HASH $PG_ADMIN_USER"
      /usr/sbin/useradd -m -s /bin/bash $USER_ARGS
      /usr/sbin/usermod $USER_ARGS
    fi

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    <% if lifecycle and lifecycle.nfs_server %>
    mkdir -p $SNAPSHOT_DIR
    check_mount "$MT_OPTS" "$MT_EXPORT" "$SNAPSHOT_DIR"
    <% end %>


    exec /var/vcap/packages/postgresql_gateway/bin/services/postgresql_gateway \
         -c $JOB_DIR/config/postgresql_gateway.yml \
         >>$LOG_DIR/postgresql_gateway.stdout.log \
         2>>$LOG_DIR/postgresql_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    <% if lifecycle and lifecycle.nfs_server %>
    umount $SNAPSHOT_DIR
    <% end %>

    ;;

  *)
    echo "Usage: $0 {start|stop}"

    ;;

esac
