#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/rds_mysql_gateway
LOG_DIR=/var/vcap/sys/log/rds_mysql_gateway
JOB_DIR=/var/vcap/jobs/rds_mysql_gateway

PIDFILE=$RUN_DIR/mysql_gateway.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "RDS MySQL gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/mysql_gateway/services/ng/mysql/bin/mysql_gateway \
         -c $JOB_DIR/config/mysql_gateway.yml \
         >>$LOG_DIR/mysql_gateway.stdout.log \
         2>>$LOG_DIR/mysql_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: rds_mysql_gateway_ctl {start|stop}"

    ;;

esac
